/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import java.text.DateFormat;
import javax.swing.Box;

/**
 *
 * @author Ghoul
 */
public class PanelVeterinario extends javax.swing.JFrame {

    /**
     * Creates new form PanelVeterinario
     */
    public PanelVeterinario() {
        DateFormat variableFecha = DateFormat.getDateInstance();
        initComponents();

        panelVerCitas.setVisible(false);

        menuVeterinario.add(Box.createHorizontalGlue());
        menuVeterinario.add(btnDesconectar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVeterinario = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        panelVerCitas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaVerCitas = new javax.swing.JList<>();
        btnCancelarCita = new javax.swing.JButton();
        labelCitasTotales = new javax.swing.JLabel();
        txtCitasTotales = new javax.swing.JTextField();
        btnModificarCita = new javax.swing.JButton();
        panelVerHistorial = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        panelDarCita = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaHoras = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDarCitaAnimal = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        btnDarCitaAceptar = new javax.swing.JButton();
        btnDarCitaCancelar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        menuVeterinario = new javax.swing.JMenuBar();
        btnCitas = new javax.swing.JMenu();
        btnDarCita = new javax.swing.JMenuItem();
        btnVerCitas = new javax.swing.JMenuItem();
        btnAnimales = new javax.swing.JMenu();
        btnVerAnimal = new javax.swing.JMenuItem();
        btnDesconectar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelVeterinario.setBackground(new java.awt.Color(152, 251, 152));
        panelVeterinario.setLayout(new java.awt.CardLayout());

        panelInicio.setBackground(panelVeterinario.getBackground());

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelVeterinario.add(panelInicio, "card4");

        panelVerCitas.setBackground(panelVeterinario.getBackground());

        listaVerCitas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaVerCitas);

        btnCancelarCita.setText("Cancelar cita seleccionada");

        labelCitasTotales.setText("Citas totales");

        txtCitasTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCitasTotalesActionPerformed(evt);
            }
        });

        btnModificarCita.setText("Modificar cita seleccionada");

        javax.swing.GroupLayout panelVerCitasLayout = new javax.swing.GroupLayout(panelVerCitas);
        panelVerCitas.setLayout(panelVerCitasLayout);
        panelVerCitasLayout.setHorizontalGroup(
            panelVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerCitasLayout.createSequentialGroup()
                .addGroup(panelVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVerCitasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(panelVerCitasLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labelCitasTotales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCitasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelVerCitasLayout.setVerticalGroup(
            panelVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(panelVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCitasTotales)
                    .addComponent(txtCitasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVeterinario.add(panelVerCitas, "card4");

        panelVerHistorial.setBackground(panelVeterinario.getBackground());

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jButton1.setText("Ver información completa");

        javax.swing.GroupLayout panelVerHistorialLayout = new javax.swing.GroupLayout(panelVerHistorial);
        panelVerHistorial.setLayout(panelVerHistorialLayout);
        panelVerHistorialLayout.setHorizontalGroup(
            panelVerHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerHistorialLayout.createSequentialGroup()
                .addGroup(panelVerHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelVerHistorialLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(panelVerHistorialLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelVerHistorialLayout.setVerticalGroup(
            panelVerHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerHistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVeterinario.add(panelVerHistorial, "card4");

        panelDarCita.setBackground(panelVeterinario.getBackground());

        listaHoras.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaHoras);

        jLabel2.setText("Veterinario");

        jTextField1.setEnabled(false);

        jLabel3.setText("Animal ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Asunto");

        jLabel5.setText("Día");

        jLabel6.setText("Urgente");

        jRadioButton1.setBackground(panelVeterinario.getBackground());
        jRadioButton1.setText("Sí");

        jRadioButton2.setBackground(panelVeterinario.getBackground());
        jRadioButton2.setText("No");

        jLabel7.setText("Horas disponibles");

        btnDarCitaAceptar.setText("Aceptar");

        btnDarCitaCancelar.setText("Cancelar");

        javax.swing.GroupLayout panelDarCitaLayout = new javax.swing.GroupLayout(panelDarCita);
        panelDarCita.setLayout(panelDarCitaLayout);
        panelDarCitaLayout.setHorizontalGroup(
            panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDarCitaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelDarCitaLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDarCitaLayout.createSequentialGroup()
                            .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDarCitaAnimal)))
                        .addGroup(panelDarCitaLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelDarCitaLayout.createSequentialGroup()
                        .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDarCitaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1))
                            .addComponent(btnDarCitaAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(btnDarCitaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(109, 109, 109)
                .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDarCitaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(173, 173, 173)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDarCitaLayout.setVerticalGroup(
            panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDarCitaLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDarCitaLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelDarCitaLayout.createSequentialGroup()
                        .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDarCitaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(97, 97, 97)
                        .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDarCitaAceptar)
                            .addComponent(btnDarCitaCancelar))
                        .addGap(24, 24, 24))))
        );

        panelVeterinario.add(panelDarCita, "card5");

        menuVeterinario.setBackground(new java.awt.Color(250, 250, 250));
        menuVeterinario.setToolTipText("");
        menuVeterinario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnCitas.setText("Citas");
        btnCitas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnDarCita.setText("Dar cita");
        btnDarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarCitaActionPerformed(evt);
            }
        });
        btnCitas.add(btnDarCita);

        btnVerCitas.setText("Ver citas");
        btnVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCitasActionPerformed(evt);
            }
        });
        btnCitas.add(btnVerCitas);

        menuVeterinario.add(btnCitas);

        btnAnimales.setText("Animales");
        btnAnimales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnVerAnimal.setText("Ver historial médico");
        btnVerAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAnimalActionPerformed(evt);
            }
        });
        btnAnimales.add(btnVerAnimal);

        menuVeterinario.add(btnAnimales);

        btnDesconectar.setText("Desconectar");
        btnDesconectar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDesconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesconectarMouseClicked(evt);
            }
        });
        menuVeterinario.add(btnDesconectar);

        setJMenuBar(menuVeterinario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVeterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCitasActionPerformed
        panelVeterinario.removeAll();
        panelVeterinario.add(panelVerCitas);
        panelVeterinario.repaint();
        panelVeterinario.revalidate();
    }//GEN-LAST:event_btnVerCitasActionPerformed

    private void btnDesconectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesconectarMouseClicked
        this.dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_btnDesconectarMouseClicked

    private void btnDarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarCitaActionPerformed
        panelVeterinario.removeAll();
        panelVeterinario.add(panelDarCita);
        panelVeterinario.repaint();
        panelVeterinario.revalidate();
    }//GEN-LAST:event_btnDarCitaActionPerformed

    private void btnVerAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAnimalActionPerformed
        CuadroBuscarCita cbc = new CuadroBuscarCita();
        cbc.setVisible(true);
        cbc.setLocationRelativeTo(null);
        panelVeterinario.removeAll();
        panelVeterinario.add(panelVerHistorial);
        panelVeterinario.repaint();
        panelVeterinario.revalidate();
    }//GEN-LAST:event_btnVerAnimalActionPerformed

    private void txtCitasTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCitasTotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCitasTotalesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAnimales;
    private javax.swing.JButton btnCancelarCita;
    private javax.swing.JMenu btnCitas;
    private javax.swing.JMenuItem btnDarCita;
    private javax.swing.JButton btnDarCitaAceptar;
    private javax.swing.JButton btnDarCitaCancelar;
    private javax.swing.JMenu btnDesconectar;
    private javax.swing.JButton btnModificarCita;
    private javax.swing.JMenuItem btnVerAnimal;
    private javax.swing.JMenuItem btnVerCitas;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelCitasTotales;
    private javax.swing.JList<String> listaHoras;
    private javax.swing.JList<String> listaVerCitas;
    private javax.swing.JMenuBar menuVeterinario;
    private javax.swing.JPanel panelDarCita;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelVerCitas;
    private javax.swing.JPanel panelVerHistorial;
    private javax.swing.JPanel panelVeterinario;
    private javax.swing.JTextField txtCitasTotales;
    private javax.swing.JTextField txtDarCitaAnimal;
    // End of variables declaration//GEN-END:variables
}
