/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Box;

/**
 *
 * @author Ghoul
 */
public class PanelAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form PanelVeterinario
     */
    public PanelAdministrador() {
        initComponents();

        DateFormat variableFecha = DateFormat.getDateInstance();
        Calendar cal = Calendar.getInstance();
        Date today = cal.getTime();
        cal.add(Calendar.YEAR, 1);
        Date nextYear = cal.getTime();
        jCalendarAdminDarCita.setMaxSelectableDate(nextYear);

        panelAdminVerCitas.setVisible(false);

        menuAdmin.add(Box.createHorizontalGlue());
        menuAdmin.add(btnAdminOpciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBtnAdminAñadirUsuario = new javax.swing.ButtonGroup();
        groupBtnAdminDarCita = new javax.swing.ButtonGroup();
        panelAdmin = new javax.swing.JPanel();
        panelAdminInicio = new javax.swing.JPanel();
        panelAdminDarCita = new javax.swing.JPanel();
        scrollAdminHorasDisponibles = new javax.swing.JScrollPane();
        listAdminHorasDisponibles = new javax.swing.JList<String>();
        jLabel2 = new javax.swing.JLabel();
        txtAdminDarCitaVet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAdminDarCitaAnimal = new javax.swing.JTextField();
        comboAdminDarCitaAsunto = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        radioAdminDarCitaUrgSi = new javax.swing.JRadioButton();
        radioAdminDarCitaUrgNo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        btnAdminDarCitaAceptar = new javax.swing.JButton();
        btnAdminDarCitaCancelar = new javax.swing.JButton();
        jCalendarAdminDarCita = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        panelAdminVerCitas = new javax.swing.JPanel();
        btnAdminVerCitasCancelarCita = new javax.swing.JButton();
        labelCitasTotales = new javax.swing.JLabel();
        txtAdminVerCitasTotales = new javax.swing.JTextField();
        btnAdminVerCitasModificarCita = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdminVerCitasAtenderCita = new javax.swing.JButton();
        scrollAdminVerCitas = new javax.swing.JScrollPane();
        tableAdminVerCitas = new javax.swing.JTable();
        panelAdminListarAnimales = new javax.swing.JPanel();
        btnAdminListarAniHistorial = new javax.swing.JButton();
        btnAdminListarAniMod = new javax.swing.JButton();
        btnAdminListarAniBorrar = new javax.swing.JButton();
        scrollAdminListarAnimales = new javax.swing.JScrollPane();
        tableAdminListarAnimales = new javax.swing.JTable();
        panelAdminHistorialMed = new javax.swing.JPanel();
        scrollAdminHistorialMed = new javax.swing.JScrollPane();
        tablaAdminHistorialMed = new javax.swing.JTable();
        btnAdminVerAnotacion = new javax.swing.JButton();
        panelAdminAñadirUsuario = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtAdminCrearPersonaDni = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAdminAñadirPersonaNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        radioAdminAñadirUsuPriviSi = new javax.swing.JRadioButton();
        radioAdminAñadirUsuPriviNo = new javax.swing.JRadioButton();
        btnAdminDarCitaAceptar1 = new javax.swing.JButton();
        btnAdminDarCitaCancelar1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtAdminAñadirPersonaDire = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txtAdminAñadirPersonaTlf = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txtAdminAñadirPersonaEmail = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        comboAdminAñadirPersonaEspe = new javax.swing.JComboBox<String>();
        jLabel17 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        panelAdminListarClientes = new javax.swing.JPanel();
        btnAdminListarClientesMod = new javax.swing.JButton();
        btnAdminListarClientesBorrar = new javax.swing.JButton();
        scrollAdminListarClientes = new javax.swing.JScrollPane();
        tableAdminListarClientes = new javax.swing.JTable();
        panelAdminListarVeterinarios = new javax.swing.JPanel();
        btnAdminListarVeterinariosMod = new javax.swing.JButton();
        btnAdminListarVeterinariosBorrar = new javax.swing.JButton();
        scrollAdminListarClientes1 = new javax.swing.JScrollPane();
        tableAdminListarVeterinarios = new javax.swing.JTable();
        menuAdmin = new javax.swing.JMenuBar();
        btnAdminCitas = new javax.swing.JMenu();
        btnDarCita = new javax.swing.JMenuItem();
        btnVerCitas = new javax.swing.JMenuItem();
        btnAdminAnimales = new javax.swing.JMenu();
        btnAdminAñadirAnimal = new javax.swing.JMenuItem();
        btnAdminListarAnimales = new javax.swing.JMenuItem();
        btnAdminUsuarios = new javax.swing.JMenu();
        btnAdminAñadirUsuario = new javax.swing.JMenuItem();
        btnAdminListarClientes = new javax.swing.JMenuItem();
        btnAdminListarVeterinarios = new javax.swing.JMenuItem();
        btnAdminOpciones = new javax.swing.JMenu();
        btnAdminDesconectar = new javax.swing.JMenuItem();
        btnAdminResContraseña = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAdmin.setBackground(new java.awt.Color(152, 251, 152));
        panelAdmin.setLayout(new java.awt.CardLayout());

        panelAdminInicio.setBackground(panelAdmin.getBackground());

        javax.swing.GroupLayout panelAdminInicioLayout = new javax.swing.GroupLayout(panelAdminInicio);
        panelAdminInicio.setLayout(panelAdminInicioLayout);
        panelAdminInicioLayout.setHorizontalGroup(
            panelAdminInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelAdminInicioLayout.setVerticalGroup(
            panelAdminInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelAdmin.add(panelAdminInicio, "card4");

        panelAdminDarCita.setBackground(panelAdmin.getBackground());

        listAdminHorasDisponibles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollAdminHorasDisponibles.setViewportView(listAdminHorasDisponibles);

        jLabel2.setText("Veterinario");

        txtAdminDarCitaVet.setEditable(false);
        txtAdminDarCitaVet.setBackground(panelAdminInicio.getBackground());
        txtAdminDarCitaVet.setBorder(null);
        txtAdminDarCitaVet.setDisabledTextColor(panelAdminInicio.getBackground());
        txtAdminDarCitaVet.setFocusable(false);

        jLabel3.setText("Animal ");

        txtAdminDarCitaAnimal.setBackground(panelAdminInicio.getBackground());
        txtAdminDarCitaAnimal.setBorder(null);

        comboAdminDarCitaAsunto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Asunto");

        jLabel5.setText("Día");

        jLabel6.setText("Urgente");

        radioAdminDarCitaUrgSi.setBackground(panelAdmin.getBackground());
        groupBtnAdminDarCita.add(radioAdminDarCitaUrgSi);
        radioAdminDarCitaUrgSi.setText("Sí");

        radioAdminDarCitaUrgNo.setBackground(panelAdmin.getBackground());
        groupBtnAdminDarCita.add(radioAdminDarCitaUrgNo);
        radioAdminDarCitaUrgNo.setText("No");

        jLabel7.setText("Horas disponibles");

        btnAdminDarCitaAceptar.setText("Aceptar");

        btnAdminDarCitaCancelar.setText("Cancelar");

        jCalendarAdminDarCita.setBackground(panelAdminInicio.getBackground());

        javax.swing.GroupLayout panelAdminDarCitaLayout = new javax.swing.GroupLayout(panelAdminDarCita);
        panelAdminDarCita.setLayout(panelAdminDarCitaLayout);
        panelAdminDarCitaLayout.setHorizontalGroup(
            panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                        .addComponent(btnAdminDarCitaAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdminDarCitaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jCalendarAdminDarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(comboAdminDarCitaAsunto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(radioAdminDarCitaUrgSi)
                        .addGap(18, 18, 18)
                        .addComponent(radioAdminDarCitaUrgNo))
                    .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdminDarCitaVet)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdminDarCitaAnimal)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollAdminHorasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminDarCitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(283, 283, 283))
        );
        panelAdminDarCitaLayout.setVerticalGroup(
            panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollAdminHorasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                                .addComponent(txtAdminDarCitaVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2)))
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(txtAdminDarCitaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel3)))
                        .addGap(48, 48, 48)
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboAdminDarCitaAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jCalendarAdminDarCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(radioAdminDarCitaUrgSi)
                                    .addComponent(radioAdminDarCitaUrgNo))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminDarCitaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAdminDarCitaCancelar)
                                    .addComponent(btnAdminDarCitaAceptar))))))
                .addGap(18, 18, 18))
        );

        panelAdmin.add(panelAdminDarCita, "card5");

        panelAdminVerCitas.setBackground(panelAdmin.getBackground());

        btnAdminVerCitasCancelarCita.setText("Cancelar cita seleccionada");

        labelCitasTotales.setText("Citas totales");

        txtAdminVerCitasTotales.setEditable(false);
        txtAdminVerCitasTotales.setBackground(panelAdminInicio.getBackground());
        txtAdminVerCitasTotales.setBorder(null);
        txtAdminVerCitasTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminVerCitasTotalesActionPerformed(evt);
            }
        });

        btnAdminVerCitasModificarCita.setText("Modificar cita seleccionada");

        btnAdminVerCitasAtenderCita.setText("Atender cita seleccionada");

        tableAdminVerCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminVerCitas.setViewportView(tableAdminVerCitas);

        javax.swing.GroupLayout panelAdminVerCitasLayout = new javax.swing.GroupLayout(panelAdminVerCitas);
        panelAdminVerCitas.setLayout(panelAdminVerCitasLayout);
        panelAdminVerCitasLayout.setHorizontalGroup(
            panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                .addGroup(panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                        .addGroup(panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminVerCitasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelCitasTotales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAdminVerCitasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdminVerCitasAtenderCita, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdminVerCitasModificarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdminVerCitasCancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollAdminVerCitas)))
                .addContainerGap())
        );
        panelAdminVerCitasLayout.setVerticalGroup(
            panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollAdminVerCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdminVerCitasModificarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdminVerCitasCancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAdminVerCitasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCitasTotales)
                        .addComponent(btnAdminVerCitasAtenderCita, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAdmin.add(panelAdminVerCitas, "card4");

        panelAdminListarAnimales.setBackground(panelAdmin.getBackground());

        btnAdminListarAniHistorial.setText("Ver historial médico del animal");
        btnAdminListarAniHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminListarAniHistorialActionPerformed(evt);
            }
        });

        btnAdminListarAniMod.setText("Modificar datos del animal");

        btnAdminListarAniBorrar.setText("Borrar animal seleccionado");

        tableAdminListarAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminListarAnimales.setViewportView(tableAdminListarAnimales);

        javax.swing.GroupLayout panelAdminListarAnimalesLayout = new javax.swing.GroupLayout(panelAdminListarAnimales);
        panelAdminListarAnimales.setLayout(panelAdminListarAnimalesLayout);
        panelAdminListarAnimalesLayout.setHorizontalGroup(
            panelAdminListarAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarAnimalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminListarAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollAdminListarAnimales)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminListarAnimalesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdminListarAniMod, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminListarAniHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminListarAniBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAdminListarAnimalesLayout.setVerticalGroup(
            panelAdminListarAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarAnimalesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scrollAdminListarAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdminListarAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminListarAniMod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminListarAniHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminListarAniBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        panelAdmin.add(panelAdminListarAnimales, "card4");

        panelAdminHistorialMed.setBackground(panelAdmin.getBackground());

        tablaAdminHistorialMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminHistorialMed.setViewportView(tablaAdminHistorialMed);

        btnAdminVerAnotacion.setText("Ver anotación completa");

        javax.swing.GroupLayout panelAdminHistorialMedLayout = new javax.swing.GroupLayout(panelAdminHistorialMed);
        panelAdminHistorialMed.setLayout(panelAdminHistorialMedLayout);
        panelAdminHistorialMedLayout.setHorizontalGroup(
            panelAdminHistorialMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminHistorialMedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminHistorialMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAdminHistorialMedLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdminVerAnotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollAdminHistorialMed, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAdminHistorialMedLayout.setVerticalGroup(
            panelAdminHistorialMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminHistorialMedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollAdminHistorialMed, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnAdminVerAnotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAdmin.add(panelAdminHistorialMed, "card4");

        panelAdminAñadirUsuario.setBackground(panelAdmin.getBackground());

        jLabel8.setText("DNI");

        txtAdminCrearPersonaDni.setEditable(false);
        txtAdminCrearPersonaDni.setBackground(panelAdminInicio.getBackground());
        txtAdminCrearPersonaDni.setBorder(null);
        txtAdminCrearPersonaDni.setDisabledTextColor(panelAdminInicio.getBackground());
        txtAdminCrearPersonaDni.setFocusable(false);
        txtAdminCrearPersonaDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminCrearPersonaDniActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre");

        txtAdminAñadirPersonaNombre.setBackground(panelAdminInicio.getBackground());
        txtAdminAñadirPersonaNombre.setBorder(null);

        jLabel12.setText("Privilegios de administrador");

        radioAdminAñadirUsuPriviSi.setBackground(panelAdmin.getBackground());
        groupBtnAdminAñadirUsuario.add(radioAdminAñadirUsuPriviSi);
        radioAdminAñadirUsuPriviSi.setText("Sí");

        radioAdminAñadirUsuPriviNo.setBackground(panelAdmin.getBackground());
        groupBtnAdminAñadirUsuario.add(radioAdminAñadirUsuPriviNo);
        radioAdminAñadirUsuPriviNo.setText("No");

        btnAdminDarCitaAceptar1.setText("Aceptar");

        btnAdminDarCitaCancelar1.setText("Cancelar");

        jLabel14.setText("Dirección");

        txtAdminAñadirPersonaDire.setBackground(panelAdminInicio.getBackground());
        txtAdminAñadirPersonaDire.setBorder(null);

        jLabel15.setText("Teléfono");

        txtAdminAñadirPersonaTlf.setBackground(panelAdminInicio.getBackground());
        txtAdminAñadirPersonaTlf.setBorder(null);

        jLabel16.setText("Email");

        txtAdminAñadirPersonaEmail.setBackground(panelAdminInicio.getBackground());
        txtAdminAñadirPersonaEmail.setBorder(null);

        jLabel1.setText("Especialidad");

        comboAdminAñadirPersonaEspe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setText("Contraseña");

        jPasswordField1.setBackground(panelAdminInicio.getBackground());
        jPasswordField1.setBorder(null);

        javax.swing.GroupLayout panelAdminAñadirUsuarioLayout = new javax.swing.GroupLayout(panelAdminAñadirUsuario);
        panelAdminAñadirUsuario.setLayout(panelAdminAñadirUsuarioLayout);
        panelAdminAñadirUsuarioLayout.setHorizontalGroup(
            panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAñadirUsuarioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelAdminAñadirUsuarioLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator4)
                                .addComponent(txtAdminCrearPersonaDni)))
                        .addGroup(panelAdminAñadirUsuarioLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAdminAñadirPersonaDire))
                        .addGroup(panelAdminAñadirUsuarioLayout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAdminAñadirPersonaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelAdminAñadirUsuarioLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAdminAñadirPersonaTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelAdminAñadirUsuarioLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(37, 37, 37)
                            .addComponent(radioAdminAñadirUsuPriviSi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioAdminAñadirUsuPriviNo))
                        .addGroup(panelAdminAñadirUsuarioLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboAdminAñadirPersonaEspe, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminAñadirUsuarioLayout.createSequentialGroup()
                            .addComponent(btnAdminDarCitaAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdminDarCitaCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelAdminAñadirUsuarioLayout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addComponent(jPasswordField1)))
                        .addGroup(panelAdminAñadirUsuarioLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5)
                                .addComponent(txtAdminAñadirPersonaNombre)))))
                .addGap(0, 672, Short.MAX_VALUE))
        );
        panelAdminAñadirUsuarioLayout.setVerticalGroup(
            panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAñadirUsuarioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminCrearPersonaDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAdminAñadirPersonaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(txtAdminAñadirPersonaDire, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminAñadirPersonaTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminAñadirPersonaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboAdminAñadirPersonaEspe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(radioAdminAñadirUsuPriviSi)
                    .addComponent(radioAdminAñadirUsuPriviNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(panelAdminAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminDarCitaCancelar1)
                    .addComponent(btnAdminDarCitaAceptar1))
                .addGap(18, 18, 18))
        );

        panelAdmin.add(panelAdminAñadirUsuario, "card5");

        panelAdminListarClientes.setBackground(panelAdmin.getBackground());

        btnAdminListarClientesMod.setText("Modificar datos del cliente");

        btnAdminListarClientesBorrar.setText("Borrar cliente seleccionado");

        tableAdminListarClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminListarClientes.setViewportView(tableAdminListarClientes);

        javax.swing.GroupLayout panelAdminListarClientesLayout = new javax.swing.GroupLayout(panelAdminListarClientes);
        panelAdminListarClientes.setLayout(panelAdminListarClientesLayout);
        panelAdminListarClientesLayout.setHorizontalGroup(
            panelAdminListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollAdminListarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminListarClientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdminListarClientesMod, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminListarClientesBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAdminListarClientesLayout.setVerticalGroup(
            panelAdminListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarClientesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scrollAdminListarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(panelAdminListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminListarClientesMod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminListarClientesBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        panelAdmin.add(panelAdminListarClientes, "card4");

        panelAdminListarVeterinarios.setBackground(panelAdmin.getBackground());

        btnAdminListarVeterinariosMod.setText("Modificar datos del veterinario");

        btnAdminListarVeterinariosBorrar.setText("Borrar veterinario seleccionado");

        tableAdminListarVeterinarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminListarClientes1.setViewportView(tableAdminListarVeterinarios);

        javax.swing.GroupLayout panelAdminListarVeterinariosLayout = new javax.swing.GroupLayout(panelAdminListarVeterinarios);
        panelAdminListarVeterinarios.setLayout(panelAdminListarVeterinariosLayout);
        panelAdminListarVeterinariosLayout.setHorizontalGroup(
            panelAdminListarVeterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarVeterinariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminListarVeterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollAdminListarClientes1, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminListarVeterinariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdminListarVeterinariosMod, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminListarVeterinariosBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAdminListarVeterinariosLayout.setVerticalGroup(
            panelAdminListarVeterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarVeterinariosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scrollAdminListarClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(panelAdminListarVeterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminListarVeterinariosMod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminListarVeterinariosBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        panelAdmin.add(panelAdminListarVeterinarios, "card4");

        menuAdmin.setBackground(new java.awt.Color(250, 250, 250));
        menuAdmin.setToolTipText("");
        menuAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAdminCitas.setText("Citas");
        btnAdminCitas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnDarCita.setText("Dar cita");
        btnDarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarCitaActionPerformed(evt);
            }
        });
        btnAdminCitas.add(btnDarCita);

        btnVerCitas.setText("Ver citas");
        btnVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCitasActionPerformed(evt);
            }
        });
        btnAdminCitas.add(btnVerCitas);

        menuAdmin.add(btnAdminCitas);

        btnAdminAnimales.setText("Animales");
        btnAdminAnimales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAdminAñadirAnimal.setText("Añadir animal");
        btnAdminAnimales.add(btnAdminAñadirAnimal);

        btnAdminListarAnimales.setText("Listar animales");
        btnAdminListarAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminListarAnimalesActionPerformed(evt);
            }
        });
        btnAdminAnimales.add(btnAdminListarAnimales);

        menuAdmin.add(btnAdminAnimales);

        btnAdminUsuarios.setText("Usuarios");
        btnAdminUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAdminAñadirUsuario.setText("Añadir usuario");
        btnAdminAñadirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAñadirUsuarioActionPerformed(evt);
            }
        });
        btnAdminUsuarios.add(btnAdminAñadirUsuario);

        btnAdminListarClientes.setText("Listar clientes");
        btnAdminListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminListarClientesActionPerformed(evt);
            }
        });
        btnAdminUsuarios.add(btnAdminListarClientes);

        btnAdminListarVeterinarios.setText("Listar veterinarios");
        btnAdminListarVeterinarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminListarVeterinariosActionPerformed(evt);
            }
        });
        btnAdminUsuarios.add(btnAdminListarVeterinarios);

        menuAdmin.add(btnAdminUsuarios);

        btnAdminOpciones.setText("Opciones");
        btnAdminOpciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdminOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminOpcionesMouseClicked(evt);
            }
        });

        btnAdminDesconectar.setText("Desconectar");
        btnAdminDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDesconectarActionPerformed(evt);
            }
        });
        btnAdminOpciones.add(btnAdminDesconectar);

        btnAdminResContraseña.setText("Restablecer contraseña a un usuario");
        btnAdminOpciones.add(btnAdminResContraseña);

        menuAdmin.add(btnAdminOpciones);

        setJMenuBar(menuAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCitasActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminVerCitas);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnVerCitasActionPerformed

    private void btnDarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarCitaActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminDarCita);
        panelAdmin.repaint();
        panelAdmin.revalidate();

    }//GEN-LAST:event_btnDarCitaActionPerformed

    private void txtAdminVerCitasTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminVerCitasTotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminVerCitasTotalesActionPerformed

    private void btnAdminOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminOpcionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminOpcionesMouseClicked

    private void btnAdminDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDesconectarActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminDesconectarActionPerformed

    private void btnAdminListarAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminListarAnimalesActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminListarAnimales);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminListarAnimalesActionPerformed

    private void btnAdminAñadirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAñadirUsuarioActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminAñadirUsuario);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminAñadirUsuarioActionPerformed

    private void txtAdminCrearPersonaDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminCrearPersonaDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminCrearPersonaDniActionPerformed

    private void btnAdminListarAniHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminListarAniHistorialActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminHistorialMed);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminListarAniHistorialActionPerformed

    private void btnAdminListarVeterinariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminListarVeterinariosActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminListarVeterinarios);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminListarVeterinariosActionPerformed

    private void btnAdminListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminListarClientesActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminListarClientes);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminListarClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAdminAnimales;
    private javax.swing.JMenuItem btnAdminAñadirAnimal;
    private javax.swing.JMenuItem btnAdminAñadirUsuario;
    private javax.swing.JMenu btnAdminCitas;
    private javax.swing.JButton btnAdminDarCitaAceptar;
    private javax.swing.JButton btnAdminDarCitaAceptar1;
    private javax.swing.JButton btnAdminDarCitaCancelar;
    private javax.swing.JButton btnAdminDarCitaCancelar1;
    private javax.swing.JMenuItem btnAdminDesconectar;
    private javax.swing.JButton btnAdminListarAniBorrar;
    private javax.swing.JButton btnAdminListarAniHistorial;
    private javax.swing.JButton btnAdminListarAniMod;
    private javax.swing.JMenuItem btnAdminListarAnimales;
    private javax.swing.JMenuItem btnAdminListarClientes;
    private javax.swing.JButton btnAdminListarClientesBorrar;
    private javax.swing.JButton btnAdminListarClientesMod;
    private javax.swing.JMenuItem btnAdminListarVeterinarios;
    private javax.swing.JButton btnAdminListarVeterinariosBorrar;
    private javax.swing.JButton btnAdminListarVeterinariosMod;
    private javax.swing.JMenu btnAdminOpciones;
    private javax.swing.JMenuItem btnAdminResContraseña;
    private javax.swing.JMenu btnAdminUsuarios;
    private javax.swing.JButton btnAdminVerAnotacion;
    private javax.swing.JButton btnAdminVerCitasAtenderCita;
    private javax.swing.JButton btnAdminVerCitasCancelarCita;
    private javax.swing.JButton btnAdminVerCitasModificarCita;
    private javax.swing.JMenuItem btnDarCita;
    private javax.swing.JMenuItem btnVerCitas;
    private javax.swing.JComboBox<String> comboAdminAñadirPersonaEspe;
    private javax.swing.JComboBox<String> comboAdminDarCitaAsunto;
    private javax.swing.ButtonGroup groupBtnAdminAñadirUsuario;
    private javax.swing.ButtonGroup groupBtnAdminDarCita;
    private com.toedter.calendar.JDateChooser jCalendarAdminDarCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel labelCitasTotales;
    private javax.swing.JList<String> listAdminHorasDisponibles;
    private javax.swing.JMenuBar menuAdmin;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JPanel panelAdminAñadirUsuario;
    private javax.swing.JPanel panelAdminDarCita;
    private javax.swing.JPanel panelAdminHistorialMed;
    private javax.swing.JPanel panelAdminInicio;
    private javax.swing.JPanel panelAdminListarAnimales;
    private javax.swing.JPanel panelAdminListarClientes;
    private javax.swing.JPanel panelAdminListarVeterinarios;
    private javax.swing.JPanel panelAdminVerCitas;
    private javax.swing.JRadioButton radioAdminAñadirUsuPriviNo;
    private javax.swing.JRadioButton radioAdminAñadirUsuPriviSi;
    private javax.swing.JRadioButton radioAdminDarCitaUrgNo;
    private javax.swing.JRadioButton radioAdminDarCitaUrgSi;
    private javax.swing.JScrollPane scrollAdminHistorialMed;
    private javax.swing.JScrollPane scrollAdminHorasDisponibles;
    private javax.swing.JScrollPane scrollAdminListarAnimales;
    private javax.swing.JScrollPane scrollAdminListarClientes;
    private javax.swing.JScrollPane scrollAdminListarClientes1;
    private javax.swing.JScrollPane scrollAdminVerCitas;
    private javax.swing.JTable tablaAdminHistorialMed;
    private javax.swing.JTable tableAdminListarAnimales;
    private javax.swing.JTable tableAdminListarClientes;
    private javax.swing.JTable tableAdminListarVeterinarios;
    private javax.swing.JTable tableAdminVerCitas;
    private javax.swing.JTextField txtAdminAñadirPersonaDire;
    private javax.swing.JTextField txtAdminAñadirPersonaEmail;
    private javax.swing.JTextField txtAdminAñadirPersonaNombre;
    private javax.swing.JTextField txtAdminAñadirPersonaTlf;
    private javax.swing.JTextField txtAdminCrearPersonaDni;
    private javax.swing.JTextField txtAdminDarCitaAnimal;
    private javax.swing.JTextField txtAdminDarCitaVet;
    private javax.swing.JTextField txtAdminVerCitasTotales;
    // End of variables declaration//GEN-END:variables
}
