/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

/**
 *
 * @author Enrique Moya García
 */
public class DialogModificarCliente extends javax.swing.JDialog {

    /**
     * Creates new form DialogModificarVeterinario
     */
    public DialogModificarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogModificarVeterinario = new javax.swing.JPanel();
        txtDialogModClienteDni = new javax.swing.JTextField();
        txtDialogModClienteNombre = new javax.swing.JTextField();
        btnDialogModVetAceptar = new javax.swing.JButton();
        btnDialogModVetPriviCancelar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtDialogModClienteDire = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtDialogModClienteTlf = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txtDialogModClienteEmail = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dialogModificarVeterinario.setBackground(new java.awt.Color(255, 204, 204));

        txtDialogModClienteDni.setEditable(false);
        txtDialogModClienteDni.setBackground(dialogModificarVeterinario.getBackground());
        txtDialogModClienteDni.setText("DNI");
        txtDialogModClienteDni.setBorder(null);
        txtDialogModClienteDni.setFocusable(false);
        txtDialogModClienteDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDialogModClienteDniActionPerformed(evt);
            }
        });

        txtDialogModClienteNombre.setBackground(dialogModificarVeterinario.getBackground());
        txtDialogModClienteNombre.setText("Nombre");
        txtDialogModClienteNombre.setBorder(null);

        btnDialogModVetAceptar.setText("Aceptar");
        btnDialogModVetAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialogModVetAceptarActionPerformed(evt);
            }
        });

        btnDialogModVetPriviCancelar.setText("Cancelar");

        txtDialogModClienteDire.setBackground(dialogModificarVeterinario.getBackground());
        txtDialogModClienteDire.setText("Dirección");
        txtDialogModClienteDire.setBorder(null);
        txtDialogModClienteDire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDialogModClienteDireActionPerformed(evt);
            }
        });

        txtDialogModClienteTlf.setBackground(dialogModificarVeterinario.getBackground());
        txtDialogModClienteTlf.setText("Teléfono");
        txtDialogModClienteTlf.setBorder(null);

        txtDialogModClienteEmail.setBackground(dialogModificarVeterinario.getBackground());
        txtDialogModClienteEmail.setText("Email");
        txtDialogModClienteEmail.setBorder(null);

        javax.swing.GroupLayout dialogModificarVeterinarioLayout = new javax.swing.GroupLayout(dialogModificarVeterinario);
        dialogModificarVeterinario.setLayout(dialogModificarVeterinarioLayout);
        dialogModificarVeterinarioLayout.setHorizontalGroup(
            dialogModificarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogModificarVeterinarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogModificarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDialogModClienteTlf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDialogModClienteEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogModificarVeterinarioLayout.createSequentialGroup()
                        .addComponent(btnDialogModVetAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDialogModVetPriviCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDialogModClienteDire, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDialogModClienteNombre)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDialogModClienteDni)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        dialogModificarVeterinarioLayout.setVerticalGroup(
            dialogModificarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogModificarVeterinarioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtDialogModClienteDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDialogModClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(txtDialogModClienteDire, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDialogModClienteTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDialogModClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogModificarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDialogModVetAceptar)
                    .addComponent(btnDialogModVetPriviCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dialogModificarVeterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(dialogModificarVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDialogModClienteDireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDialogModClienteDireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDialogModClienteDireActionPerformed

    private void btnDialogModVetAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogModVetAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDialogModVetAceptarActionPerformed

    private void txtDialogModClienteDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDialogModClienteDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDialogModClienteDniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogModificarCliente dialog = new DialogModificarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDialogModVetAceptar;
    private javax.swing.JButton btnDialogModVetPriviCancelar;
    private javax.swing.JPanel dialogModificarVeterinario;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField txtDialogModClienteDire;
    private javax.swing.JTextField txtDialogModClienteDni;
    private javax.swing.JTextField txtDialogModClienteEmail;
    private javax.swing.JTextField txtDialogModClienteNombre;
    private javax.swing.JTextField txtDialogModClienteTlf;
    // End of variables declaration//GEN-END:variables
}
