/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

/**
 *
 * @author Enrique Moya García
 */
public class DialogModificarVeterinario extends javax.swing.JDialog {

    /**
     * Creates new form DialogModificarVeterinario
     */
    public DialogModificarVeterinario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogModificarVeterinario = new javax.swing.JPanel();
        txtDialogModVetDni = new javax.swing.JTextField();
        txtDialogModVetNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        radioDialogModVetPriviSi = new javax.swing.JRadioButton();
        radioDialogModVetPriviNo = new javax.swing.JRadioButton();
        btnDialogModVetAceptar = new javax.swing.JButton();
        btnDialogModVetPriviCancelar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtDialogModVetDire = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtDialogModVetTlf = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txtDialogModVetEmail = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        comboDialogModVetEspe = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dialogModificarVeterinario.setBackground(new java.awt.Color(255, 204, 204));

        txtDialogModVetDni.setEditable(false);
        txtDialogModVetDni.setBackground(dialogModificarVeterinario.getBackground());
        txtDialogModVetDni.setText("DNI");
        txtDialogModVetDni.setBorder(null);
        txtDialogModVetDni.setFocusable(false);
        txtDialogModVetDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDialogModVetDniActionPerformed(evt);
            }
        });

        txtDialogModVetNombre.setBackground(dialogModificarVeterinario.getBackground());
        txtDialogModVetNombre.setText("Nombre");
        txtDialogModVetNombre.setBorder(null);

        jLabel12.setText("Privilegios de administrador");

        radioDialogModVetPriviSi.setBackground(dialogModificarVeterinario.getBackground());
        radioDialogModVetPriviSi.setText("Sí");

        radioDialogModVetPriviNo.setBackground(dialogModificarVeterinario.getBackground());
        radioDialogModVetPriviNo.setText("No");

        btnDialogModVetAceptar.setText("Aceptar");
        btnDialogModVetAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialogModVetAceptarActionPerformed(evt);
            }
        });

        btnDialogModVetPriviCancelar.setText("Cancelar");

        txtDialogModVetDire.setBackground(dialogModificarVeterinario.getBackground());
        txtDialogModVetDire.setText("Dirección");
        txtDialogModVetDire.setBorder(null);
        txtDialogModVetDire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDialogModVetDireActionPerformed(evt);
            }
        });

        txtDialogModVetTlf.setBackground(dialogModificarVeterinario.getBackground());
        txtDialogModVetTlf.setText("Teléfono");
        txtDialogModVetTlf.setBorder(null);

        txtDialogModVetEmail.setBackground(dialogModificarVeterinario.getBackground());
        txtDialogModVetEmail.setText("Email");
        txtDialogModVetEmail.setBorder(null);

        jLabel1.setText("Especialidad");

        comboDialogModVetEspe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout dialogModificarVeterinarioLayout = new javax.swing.GroupLayout(dialogModificarVeterinario);
        dialogModificarVeterinario.setLayout(dialogModificarVeterinarioLayout);
        dialogModificarVeterinarioLayout.setHorizontalGroup(
            dialogModificarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogModificarVeterinarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogModificarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDialogModVetTlf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDialogModVetEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogModificarVeterinarioLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(37, 37, 37)
                        .addComponent(radioDialogModVetPriviSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioDialogModVetPriviNo))
                    .addGroup(dialogModificarVeterinarioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboDialogModVetEspe, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogModificarVeterinarioLayout.createSequentialGroup()
                        .addComponent(btnDialogModVetAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDialogModVetPriviCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDialogModVetDire, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDialogModVetNombre)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDialogModVetDni)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        dialogModificarVeterinarioLayout.setVerticalGroup(
            dialogModificarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogModificarVeterinarioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtDialogModVetDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDialogModVetNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(txtDialogModVetDire, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDialogModVetTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDialogModVetEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(dialogModificarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboDialogModVetEspe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(dialogModificarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(radioDialogModVetPriviSi)
                    .addComponent(radioDialogModVetPriviNo))
                .addGap(18, 18, 18)
                .addGroup(dialogModificarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDialogModVetAceptar)
                    .addComponent(btnDialogModVetPriviCancelar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dialogModificarVeterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dialogModificarVeterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDialogModVetDireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDialogModVetDireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDialogModVetDireActionPerformed

    private void btnDialogModVetAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogModVetAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDialogModVetAceptarActionPerformed

    private void txtDialogModVetDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDialogModVetDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDialogModVetDniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogModificarVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogModificarVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogModificarVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogModificarVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogModificarVeterinario dialog = new DialogModificarVeterinario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDialogModVetAceptar;
    private javax.swing.JButton btnDialogModVetPriviCancelar;
    private javax.swing.JComboBox<String> comboDialogModVetEspe;
    private javax.swing.JPanel dialogModificarVeterinario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JRadioButton radioDialogModVetPriviNo;
    private javax.swing.JRadioButton radioDialogModVetPriviSi;
    private javax.swing.JTextField txtDialogModVetDire;
    private javax.swing.JTextField txtDialogModVetDni;
    private javax.swing.JTextField txtDialogModVetEmail;
    private javax.swing.JTextField txtDialogModVetNombre;
    private javax.swing.JTextField txtDialogModVetTlf;
    // End of variables declaration//GEN-END:variables
}
