/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import java.awt.Color;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Box;

/**
 *
 * @author Ghoul
 */
public class PanelAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form PanelVeterinario
     */
    int r = 0;
    int g = 0;
    int b = 0;

    public PanelAdministrador() {
        initComponents();

        DateFormat variableFecha = DateFormat.getDateInstance();
        Calendar cal = Calendar.getInstance();
        Date today = cal.getTime();
        cal.add(Calendar.YEAR, 1);
        Date nextYear = cal.getTime();
        jCalendarAdminDarCita.setMaxSelectableDate(nextYear);

        panelAdminVerCitas.setVisible(false);

        menuAdmin.add(Box.createHorizontalGlue());
        menuAdmin.add(btnAdminOpciones);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBtnAdminAnadirUsuario = new javax.swing.ButtonGroup();
        groupBtnAdminDarCita = new javax.swing.ButtonGroup();
        panelAdmin = new javax.swing.JPanel();
        panelAdminInicio = new javax.swing.JPanel();
        panelAdminDarCita = new javax.swing.JPanel();
        scrollAdminHorasDisponibles = new javax.swing.JScrollPane();
        listAdminHorasDisponibles = new javax.swing.JList<>();
        txtAdminDarCitaVet = new javax.swing.JTextField();
        txtAdminDarCitaAnimal = new javax.swing.JTextField();
        comboAdminDarCitaAsunto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAdminDarCitaAceptar = new javax.swing.JButton();
        btnAdminDarCitaCancelar = new javax.swing.JButton();
        jCalendarAdminDarCita = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        panelAdminVerCitas = new javax.swing.JPanel();
        btnAdminVerCitasCancelarCita = new javax.swing.JButton();
        labelCitasTotales = new javax.swing.JLabel();
        txtAdminVerCitasTotales = new javax.swing.JTextField();
        btnAdminVerCitasModificarCita = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdminVerCitasAtenderCita = new javax.swing.JButton();
        scrollAdminVerCitas = new javax.swing.JScrollPane();
        tableAdminVerCitas = new javax.swing.JTable();
        panelAdminListarAnimales = new javax.swing.JPanel();
        btnAdminListarAniHistorial = new javax.swing.JButton();
        btnAdminListarAniMod = new javax.swing.JButton();
        btnAdminListarAniBorrar = new javax.swing.JButton();
        scrollAdminListarAnimales = new javax.swing.JScrollPane();
        tableAdminListarAnimales = new javax.swing.JTable();
        panelAdminHistorialMed = new javax.swing.JPanel();
        scrollAdminHistorialMed = new javax.swing.JScrollPane();
        tablaAdminHistorialMed = new javax.swing.JTable();
        btnAdminVerAnotacion = new javax.swing.JButton();
        panelAdminAnadirVeterinario = new javax.swing.JPanel();
        txtAdminCrearPersonaDni = new javax.swing.JTextField();
        txtAdminAnadirPersonaNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        radioAdminAnadirUsuPriviSi = new javax.swing.JRadioButton();
        radioAdminAnadirUsuPriviNo = new javax.swing.JRadioButton();
        btnAdminDarCitaAceptar1 = new javax.swing.JButton();
        btnAdminDarCitaCancelar1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtAdminAnadirPersonaDire = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtAdminAnadirPersonaTlf = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txtAdminAnadirPersonaEmail = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        comboAdminAnadirPersonaEspe = new javax.swing.JComboBox<>();
        jSeparator9 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        panelAdminListarClientes = new javax.swing.JPanel();
        btnAdminListarClientesMod = new javax.swing.JButton();
        btnAdminListarClientesBorrar = new javax.swing.JButton();
        scrollAdminListarClientes = new javax.swing.JScrollPane();
        tableAdminListarClientes = new javax.swing.JTable();
        panelAdminListarVeterinarios = new javax.swing.JPanel();
        btnAdminListarVeterinariosMod = new javax.swing.JButton();
        btnAdminListarVeterinariosBorrar = new javax.swing.JButton();
        scrollAdminListarClientes1 = new javax.swing.JScrollPane();
        tableAdminListarVeterinarios = new javax.swing.JTable();
        panelAdminAnadirAnimal = new javax.swing.JPanel();
        txtAdminAnadirAnimalId = new javax.swing.JTextField();
        txtAdminAnadirAnimalNombre = new javax.swing.JTextField();
        btnAdminDarCitaAceptar2 = new javax.swing.JButton();
        btnAdminDarCitaCancelar2 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        txtAdminAnadirAnimalRaza = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        txtAdminAnadirAnimalEspecie = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        spinnerAdminAnadirAnimalPeso = new javax.swing.JSpinner();
        calendarAdminAnadirAnimalNacimiento = new com.toedter.calendar.JDateChooser();
        txtAdminAnadirAnimalEspecie1 = new javax.swing.JTextField();
        panelAdminAnadirCliente = new javax.swing.JPanel();
        txtAdminCrearPersonaDni1 = new javax.swing.JTextField();
        txtAdminAnadirPersonaNombre1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        radioAdminAnadirUsuPriviSi1 = new javax.swing.JRadioButton();
        radioAdminAnadirUsuPriviNo1 = new javax.swing.JRadioButton();
        btnAdminDarCitaAceptar3 = new javax.swing.JButton();
        btnAdminDarCitaCancelar3 = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        txtAdminAnadirPersonaDire1 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        txtAdminAnadirPersonaTlf1 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        txtAdminAnadirPersonaEmail1 = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jPasswordField2 = new javax.swing.JPasswordField();
        menuAdmin = new javax.swing.JMenuBar();
        btnAdminCitas = new javax.swing.JMenu();
        btnDarCita = new javax.swing.JMenuItem();
        btnVerCitas = new javax.swing.JMenuItem();
        btnAdminAnimales = new javax.swing.JMenu();
        btnAdminAnadirAnimal = new javax.swing.JMenuItem();
        btnAdminListarAnimales = new javax.swing.JMenuItem();
        btnAdminUsuarios = new javax.swing.JMenu();
        btnAdminAnadirCliente = new javax.swing.JMenuItem();
        btnAdminAnadirVeterinario = new javax.swing.JMenuItem();
        btnAdminListarClientes = new javax.swing.JMenuItem();
        btnAdminListarVeterinarios = new javax.swing.JMenuItem();
        btnAdminOpciones = new javax.swing.JMenu();
        btnAdminDesconectar = new javax.swing.JMenuItem();
        btnAdminResContrasena = new javax.swing.JMenuItem();
        menuElegirTema = new javax.swing.JMenu();
        btnElegirTemaSalmon = new javax.swing.JMenuItem();
        btnElegirTemaAzul = new javax.swing.JMenuItem();
        btnElegirTemaVerde = new javax.swing.JMenuItem();
        btnElegirTemaCustom = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAdmin.setBackground(new java.awt.Color(255, 204, 204));
        panelAdmin.setLayout(new java.awt.CardLayout());

        panelAdminInicio.setBackground(panelAdmin.getBackground());

        javax.swing.GroupLayout panelAdminInicioLayout = new javax.swing.GroupLayout(panelAdminInicio);
        panelAdminInicio.setLayout(panelAdminInicioLayout);
        panelAdminInicioLayout.setHorizontalGroup(
            panelAdminInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelAdminInicioLayout.setVerticalGroup(
            panelAdminInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelAdmin.add(panelAdminInicio, "card4");

        panelAdminDarCita.setBackground(panelAdmin.getBackground());

        listAdminHorasDisponibles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollAdminHorasDisponibles.setViewportView(listAdminHorasDisponibles);

        txtAdminDarCitaVet.setEditable(false);
        txtAdminDarCitaVet.setBackground(panelAdmin.getBackground());
        txtAdminDarCitaVet.setText("Veterinario");
        txtAdminDarCitaVet.setBorder(null);
        txtAdminDarCitaVet.setDisabledTextColor(panelAdminInicio.getBackground());
        txtAdminDarCitaVet.setFocusable(false);

        txtAdminDarCitaAnimal.setBackground(panelAdmin.getBackground());
        txtAdminDarCitaAnimal.setText("Animal");
        txtAdminDarCitaAnimal.setBorder(null);

        comboAdminDarCitaAsunto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Asunto");

        jLabel5.setText("Día");

        jLabel7.setText("Horas disponibles");

        btnAdminDarCitaAceptar.setText("Aceptar");

        btnAdminDarCitaCancelar.setText("Cancelar");

        jCalendarAdminDarCita.setBackground(panelAdminInicio.getBackground());

        javax.swing.GroupLayout panelAdminDarCitaLayout = new javax.swing.GroupLayout(panelAdminDarCita);
        panelAdminDarCita.setLayout(panelAdminDarCitaLayout);
        panelAdminDarCitaLayout.setHorizontalGroup(
            panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAdminDarCitaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                            .addComponent(btnAdminDarCitaAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)
                            .addComponent(btnAdminDarCitaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(comboAdminDarCitaAsunto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(4, 4, 4)))
                    .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(jCalendarAdminDarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdminDarCitaVet, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollAdminHorasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminDarCitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(238, 238, 238))
        );
        panelAdminDarCitaLayout.setVerticalGroup(
            panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollAdminHorasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                        .addComponent(txtAdminDarCitaVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtAdminDarCitaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboAdminDarCitaAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(69, 69, 69)
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalendarAdminDarCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdminDarCitaCancelar)
                            .addComponent(btnAdminDarCitaAceptar))))
                .addGap(18, 18, 18))
        );

        panelAdmin.add(panelAdminDarCita, "card5");

        panelAdminVerCitas.setBackground(panelAdmin.getBackground());

        btnAdminVerCitasCancelarCita.setText("Cancelar cita seleccionada");

        labelCitasTotales.setText("Citas totales");

        txtAdminVerCitasTotales.setEditable(false);
        txtAdminVerCitasTotales.setBackground(panelAdmin.getBackground());
        txtAdminVerCitasTotales.setBorder(null);
        txtAdminVerCitasTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminVerCitasTotalesActionPerformed(evt);
            }
        });

        btnAdminVerCitasModificarCita.setText("Modificar cita seleccionada");
        btnAdminVerCitasModificarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminVerCitasModificarCitaActionPerformed(evt);
            }
        });

        btnAdminVerCitasAtenderCita.setText("Atender cita seleccionada");

        tableAdminVerCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminVerCitas.setViewportView(tableAdminVerCitas);

        javax.swing.GroupLayout panelAdminVerCitasLayout = new javax.swing.GroupLayout(panelAdminVerCitas);
        panelAdminVerCitas.setLayout(panelAdminVerCitasLayout);
        panelAdminVerCitasLayout.setHorizontalGroup(
            panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                .addGroup(panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                        .addGroup(panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminVerCitasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelCitasTotales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAdminVerCitasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdminVerCitasAtenderCita, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdminVerCitasModificarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdminVerCitasCancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollAdminVerCitas)))
                .addContainerGap())
        );
        panelAdminVerCitasLayout.setVerticalGroup(
            panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollAdminVerCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdminVerCitasModificarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdminVerCitasCancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAdminVerCitasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCitasTotales)
                        .addComponent(btnAdminVerCitasAtenderCita, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAdmin.add(panelAdminVerCitas, "card4");

        panelAdminListarAnimales.setBackground(panelAdmin.getBackground());

        btnAdminListarAniHistorial.setText("Ver historial médico del animal");
        btnAdminListarAniHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminListarAniHistorialActionPerformed(evt);
            }
        });

        btnAdminListarAniMod.setText("Modificar datos del animal");

        btnAdminListarAniBorrar.setText("Borrar animal seleccionado");

        tableAdminListarAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminListarAnimales.setViewportView(tableAdminListarAnimales);

        javax.swing.GroupLayout panelAdminListarAnimalesLayout = new javax.swing.GroupLayout(panelAdminListarAnimales);
        panelAdminListarAnimales.setLayout(panelAdminListarAnimalesLayout);
        panelAdminListarAnimalesLayout.setHorizontalGroup(
            panelAdminListarAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarAnimalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminListarAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollAdminListarAnimales)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminListarAnimalesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdminListarAniMod, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminListarAniHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminListarAniBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAdminListarAnimalesLayout.setVerticalGroup(
            panelAdminListarAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarAnimalesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scrollAdminListarAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdminListarAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminListarAniMod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminListarAniHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminListarAniBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        panelAdmin.add(panelAdminListarAnimales, "card4");

        panelAdminHistorialMed.setBackground(panelAdmin.getBackground());

        tablaAdminHistorialMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminHistorialMed.setViewportView(tablaAdminHistorialMed);

        btnAdminVerAnotacion.setText("Ver anotación completa");

        javax.swing.GroupLayout panelAdminHistorialMedLayout = new javax.swing.GroupLayout(panelAdminHistorialMed);
        panelAdminHistorialMed.setLayout(panelAdminHistorialMedLayout);
        panelAdminHistorialMedLayout.setHorizontalGroup(
            panelAdminHistorialMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminHistorialMedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminHistorialMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAdminHistorialMedLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdminVerAnotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollAdminHistorialMed, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAdminHistorialMedLayout.setVerticalGroup(
            panelAdminHistorialMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminHistorialMedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollAdminHistorialMed, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnAdminVerAnotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAdmin.add(panelAdminHistorialMed, "card4");

        panelAdminAnadirVeterinario.setBackground(panelAdmin.getBackground());

        txtAdminCrearPersonaDni.setEditable(false);
        txtAdminCrearPersonaDni.setBackground(panelAdmin.getBackground());
        txtAdminCrearPersonaDni.setText("DNI");
        txtAdminCrearPersonaDni.setBorder(null);
        txtAdminCrearPersonaDni.setDisabledTextColor(panelAdminInicio.getBackground());
        txtAdminCrearPersonaDni.setFocusable(false);
        txtAdminCrearPersonaDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminCrearPersonaDniActionPerformed(evt);
            }
        });

        txtAdminAnadirPersonaNombre.setBackground(panelAdmin.getBackground());
        txtAdminAnadirPersonaNombre.setText("Nombre");
        txtAdminAnadirPersonaNombre.setBorder(null);

        jLabel12.setText("Privilegios de administrador");

        radioAdminAnadirUsuPriviSi.setBackground(panelAdmin.getBackground());
        groupBtnAdminAnadirUsuario.add(radioAdminAnadirUsuPriviSi);
        radioAdminAnadirUsuPriviSi.setText("Sí");

        radioAdminAnadirUsuPriviNo.setBackground(panelAdmin.getBackground());
        groupBtnAdminAnadirUsuario.add(radioAdminAnadirUsuPriviNo);
        radioAdminAnadirUsuPriviNo.setText("No");

        btnAdminDarCitaAceptar1.setText("Aceptar");

        btnAdminDarCitaCancelar1.setText("Cancelar");

        txtAdminAnadirPersonaDire.setBackground(panelAdmin.getBackground());
        txtAdminAnadirPersonaDire.setText("Dirección");
        txtAdminAnadirPersonaDire.setBorder(null);

        txtAdminAnadirPersonaTlf.setBackground(panelAdmin.getBackground());
        txtAdminAnadirPersonaTlf.setText("Teléfono");
        txtAdminAnadirPersonaTlf.setBorder(null);

        txtAdminAnadirPersonaEmail.setBackground(panelAdmin.getBackground());
        txtAdminAnadirPersonaEmail.setText("Email");
        txtAdminAnadirPersonaEmail.setBorder(null);

        jLabel1.setText("Especialidad");

        comboAdminAnadirPersonaEspe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPasswordField1.setBackground(panelAdmin.getBackground());
        jPasswordField1.setText("Contrasena");
        jPasswordField1.setToolTipText("");
        jPasswordField1.setBorder(null);

        javax.swing.GroupLayout panelAdminAnadirVeterinarioLayout = new javax.swing.GroupLayout(panelAdminAnadirVeterinario);
        panelAdminAnadirVeterinario.setLayout(panelAdminAnadirVeterinarioLayout);
        panelAdminAnadirVeterinarioLayout.setHorizontalGroup(
            panelAdminAnadirVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAnadirVeterinarioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelAdminAnadirVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAdminAnadirPersonaTlf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAnadirPersonaEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAdminAnadirVeterinarioLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(37, 37, 37)
                        .addComponent(radioAdminAnadirUsuPriviSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioAdminAnadirUsuPriviNo))
                    .addGroup(panelAdminAnadirVeterinarioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboAdminAnadirPersonaEspe, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminAnadirVeterinarioLayout.createSequentialGroup()
                        .addComponent(btnAdminDarCitaAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdminDarCitaCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAnadirPersonaDire, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAnadirPersonaNombre)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminCrearPersonaDni)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator9)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAdminAnadirVeterinarioLayout.setVerticalGroup(
            panelAdminAnadirVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAnadirVeterinarioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtAdminCrearPersonaDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdminAnadirPersonaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(txtAdminAnadirPersonaDire, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdminAnadirPersonaTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAdminAnadirPersonaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(panelAdminAnadirVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboAdminAnadirPersonaEspe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdminAnadirVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(radioAdminAnadirUsuPriviSi)
                    .addComponent(radioAdminAnadirUsuPriviNo))
                .addGap(18, 18, 18)
                .addGroup(panelAdminAnadirVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminDarCitaCancelar1)
                    .addComponent(btnAdminDarCitaAceptar1))
                .addGap(18, 18, 18))
        );

        panelAdmin.add(panelAdminAnadirVeterinario, "card5");

        panelAdminListarClientes.setBackground(panelAdmin.getBackground());

        btnAdminListarClientesMod.setText("Modificar datos del cliente");

        btnAdminListarClientesBorrar.setText("Borrar cliente seleccionado");

        tableAdminListarClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminListarClientes.setViewportView(tableAdminListarClientes);

        javax.swing.GroupLayout panelAdminListarClientesLayout = new javax.swing.GroupLayout(panelAdminListarClientes);
        panelAdminListarClientes.setLayout(panelAdminListarClientesLayout);
        panelAdminListarClientesLayout.setHorizontalGroup(
            panelAdminListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollAdminListarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminListarClientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdminListarClientesMod, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminListarClientesBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAdminListarClientesLayout.setVerticalGroup(
            panelAdminListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarClientesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scrollAdminListarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdminListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminListarClientesMod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminListarClientesBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        panelAdmin.add(panelAdminListarClientes, "card4");

        panelAdminListarVeterinarios.setBackground(panelAdmin.getBackground());

        btnAdminListarVeterinariosMod.setText("Modificar datos del veterinario");

        btnAdminListarVeterinariosBorrar.setText("Borrar veterinario seleccionado");

        tableAdminListarVeterinarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminListarClientes1.setViewportView(tableAdminListarVeterinarios);

        javax.swing.GroupLayout panelAdminListarVeterinariosLayout = new javax.swing.GroupLayout(panelAdminListarVeterinarios);
        panelAdminListarVeterinarios.setLayout(panelAdminListarVeterinariosLayout);
        panelAdminListarVeterinariosLayout.setHorizontalGroup(
            panelAdminListarVeterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarVeterinariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminListarVeterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollAdminListarClientes1)
                    .addGroup(panelAdminListarVeterinariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdminListarVeterinariosMod, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnAdminListarVeterinariosBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAdminListarVeterinariosLayout.setVerticalGroup(
            panelAdminListarVeterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarVeterinariosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scrollAdminListarClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdminListarVeterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminListarVeterinariosMod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminListarVeterinariosBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        panelAdmin.add(panelAdminListarVeterinarios, "card4");

        panelAdminAnadirAnimal.setBackground(panelAdmin.getBackground());

        txtAdminAnadirAnimalId.setEditable(false);
        txtAdminAnadirAnimalId.setBackground(panelAdminInicio.getBackground());
        txtAdminAnadirAnimalId.setText("ID");
        txtAdminAnadirAnimalId.setBorder(null);
        txtAdminAnadirAnimalId.setDisabledTextColor(panelAdminInicio.getBackground());
        txtAdminAnadirAnimalId.setFocusable(false);
        txtAdminAnadirAnimalId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminAnadirAnimalIdActionPerformed(evt);
            }
        });

        txtAdminAnadirAnimalNombre.setBackground(panelAdminInicio.getBackground());
        txtAdminAnadirAnimalNombre.setText("Nombre");
        txtAdminAnadirAnimalNombre.setBorder(null);

        btnAdminDarCitaAceptar2.setText("Aceptar");

        btnAdminDarCitaCancelar2.setText("Cancelar");

        txtAdminAnadirAnimalRaza.setBackground(panelAdminInicio.getBackground());
        txtAdminAnadirAnimalRaza.setText("Raza");
        txtAdminAnadirAnimalRaza.setBorder(null);

        txtAdminAnadirAnimalEspecie.setBackground(panelAdminInicio.getBackground());
        txtAdminAnadirAnimalEspecie.setText("Especie");
        txtAdminAnadirAnimalEspecie.setBorder(null);

        jLabel20.setText("Peso");

        jLabel21.setText("Fecha de nacimiento");

        spinnerAdminAnadirAnimalPeso.setModel(new javax.swing.SpinnerNumberModel(1.0f, 1.0f, null, 1.0f));

        calendarAdminAnadirAnimalNacimiento.setBackground(panelAdminInicio.getBackground());

        txtAdminAnadirAnimalEspecie1.setBackground(panelAdminInicio.getBackground());
        txtAdminAnadirAnimalEspecie1.setText("Dueno");
        txtAdminAnadirAnimalEspecie1.setBorder(null);

        javax.swing.GroupLayout panelAdminAnadirAnimalLayout = new javax.swing.GroupLayout(panelAdminAnadirAnimal);
        panelAdminAnadirAnimal.setLayout(panelAdminAnadirAnimalLayout);
        panelAdminAnadirAnimalLayout.setHorizontalGroup(
            panelAdminAnadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAnadirAnimalLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelAdminAnadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminAnadirAnimalLayout.createSequentialGroup()
                        .addComponent(btnAdminDarCitaAceptar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(btnAdminDarCitaCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator10)
                    .addComponent(txtAdminAnadirAnimalId)
                    .addComponent(jSeparator11)
                    .addComponent(txtAdminAnadirAnimalNombre)
                    .addComponent(txtAdminAnadirAnimalRaza)
                    .addComponent(txtAdminAnadirAnimalEspecie)
                    .addComponent(jSeparator15)
                    .addComponent(txtAdminAnadirAnimalEspecie1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAdminAnadirAnimalLayout.createSequentialGroup()
                        .addGroup(panelAdminAnadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAdminAnadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerAdminAnadirAnimalPeso)
                            .addComponent(calendarAdminAnadirAnimalNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAdminAnadirAnimalLayout.setVerticalGroup(
            panelAdminAnadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAnadirAnimalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtAdminAnadirAnimalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdminAnadirAnimalNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(txtAdminAnadirAnimalRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdminAnadirAnimalEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAdminAnadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(spinnerAdminAnadirAnimalPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelAdminAnadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(calendarAdminAnadirAnimalNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(txtAdminAnadirAnimalEspecie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(panelAdminAnadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminDarCitaAceptar2)
                    .addComponent(btnAdminDarCitaCancelar2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAdmin.add(panelAdminAnadirAnimal, "card5");

        panelAdminAnadirCliente.setBackground(panelAdmin.getBackground());

        txtAdminCrearPersonaDni1.setEditable(false);
        txtAdminCrearPersonaDni1.setBackground(panelAdmin.getBackground());
        txtAdminCrearPersonaDni1.setText("DNI");
        txtAdminCrearPersonaDni1.setBorder(null);
        txtAdminCrearPersonaDni1.setDisabledTextColor(panelAdminInicio.getBackground());
        txtAdminCrearPersonaDni1.setFocusable(false);
        txtAdminCrearPersonaDni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminCrearPersonaDni1ActionPerformed(evt);
            }
        });

        txtAdminAnadirPersonaNombre1.setBackground(panelAdmin.getBackground());
        txtAdminAnadirPersonaNombre1.setText("Nombre");
        txtAdminAnadirPersonaNombre1.setBorder(null);

        jLabel13.setText("Privilegios de administrador");

        radioAdminAnadirUsuPriviSi1.setBackground(panelAdmin.getBackground());
        groupBtnAdminAnadirUsuario.add(radioAdminAnadirUsuPriviSi1);
        radioAdminAnadirUsuPriviSi1.setText("Sí");

        radioAdminAnadirUsuPriviNo1.setBackground(panelAdmin.getBackground());
        groupBtnAdminAnadirUsuario.add(radioAdminAnadirUsuPriviNo1);
        radioAdminAnadirUsuPriviNo1.setText("No");

        btnAdminDarCitaAceptar3.setText("Aceptar");

        btnAdminDarCitaCancelar3.setText("Cancelar");

        txtAdminAnadirPersonaDire1.setBackground(panelAdmin.getBackground());
        txtAdminAnadirPersonaDire1.setText("Dirección");
        txtAdminAnadirPersonaDire1.setBorder(null);

        txtAdminAnadirPersonaTlf1.setBackground(panelAdmin.getBackground());
        txtAdminAnadirPersonaTlf1.setText("Teléfono");
        txtAdminAnadirPersonaTlf1.setBorder(null);

        txtAdminAnadirPersonaEmail1.setBackground(panelAdmin.getBackground());
        txtAdminAnadirPersonaEmail1.setText("Email");
        txtAdminAnadirPersonaEmail1.setBorder(null);

        jPasswordField2.setBackground(panelAdmin.getBackground());
        jPasswordField2.setText("Contrasena");
        jPasswordField2.setToolTipText("");
        jPasswordField2.setBorder(null);

        javax.swing.GroupLayout panelAdminAnadirClienteLayout = new javax.swing.GroupLayout(panelAdminAnadirCliente);
        panelAdminAnadirCliente.setLayout(panelAdminAnadirClienteLayout);
        panelAdminAnadirClienteLayout.setHorizontalGroup(
            panelAdminAnadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAnadirClienteLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelAdminAnadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAdminAnadirPersonaTlf1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAnadirPersonaEmail1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminAnadirClienteLayout.createSequentialGroup()
                        .addComponent(btnAdminDarCitaAceptar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(btnAdminDarCitaCancelar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAnadirPersonaDire1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAnadirPersonaNombre1)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminCrearPersonaDni1)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator20)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAdminAnadirClienteLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(37, 37, 37)
                        .addComponent(radioAdminAnadirUsuPriviSi1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioAdminAnadirUsuPriviNo1)))
                .addGap(0, 672, Short.MAX_VALUE))
        );
        panelAdminAnadirClienteLayout.setVerticalGroup(
            panelAdminAnadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAnadirClienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtAdminCrearPersonaDni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdminAnadirPersonaNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(txtAdminAnadirPersonaDire1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdminAnadirPersonaTlf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAdminAnadirPersonaEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(panelAdminAnadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(radioAdminAnadirUsuPriviSi1)
                    .addComponent(radioAdminAnadirUsuPriviNo1))
                .addGap(59, 59, 59)
                .addGroup(panelAdminAnadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminDarCitaCancelar3)
                    .addComponent(btnAdminDarCitaAceptar3))
                .addGap(18, 18, 18))
        );

        panelAdmin.add(panelAdminAnadirCliente, "card5");

        menuAdmin.setBackground(new java.awt.Color(250, 250, 250));
        menuAdmin.setToolTipText("");
        menuAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAdminCitas.setText("Citas");
        btnAdminCitas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnDarCita.setText("Dar cita");
        btnDarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarCitaActionPerformed(evt);
            }
        });
        btnAdminCitas.add(btnDarCita);

        btnVerCitas.setText("Ver citas");
        btnVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCitasActionPerformed(evt);
            }
        });
        btnAdminCitas.add(btnVerCitas);

        menuAdmin.add(btnAdminCitas);

        btnAdminAnimales.setText("Animales");
        btnAdminAnimales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAdminAnadirAnimal.setText("Anadir animal");
        btnAdminAnadirAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAnadirAnimalActionPerformed(evt);
            }
        });
        btnAdminAnimales.add(btnAdminAnadirAnimal);

        btnAdminListarAnimales.setText("Listar animales");
        btnAdminListarAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminListarAnimalesActionPerformed(evt);
            }
        });
        btnAdminAnimales.add(btnAdminListarAnimales);

        menuAdmin.add(btnAdminAnimales);

        btnAdminUsuarios.setText("Usuarios");
        btnAdminUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAdminAnadirCliente.setText("Anadir cliente");
        btnAdminAnadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAnadirClienteActionPerformed(evt);
            }
        });
        btnAdminUsuarios.add(btnAdminAnadirCliente);

        btnAdminAnadirVeterinario.setText("Anadir veterinario");
        btnAdminAnadirVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAnadirVeterinarioActionPerformed(evt);
            }
        });
        btnAdminUsuarios.add(btnAdminAnadirVeterinario);

        btnAdminListarClientes.setText("Listar clientes");
        btnAdminListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminListarClientesActionPerformed(evt);
            }
        });
        btnAdminUsuarios.add(btnAdminListarClientes);

        btnAdminListarVeterinarios.setText("Listar veterinarios");
        btnAdminListarVeterinarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminListarVeterinariosActionPerformed(evt);
            }
        });
        btnAdminUsuarios.add(btnAdminListarVeterinarios);

        menuAdmin.add(btnAdminUsuarios);

        btnAdminOpciones.setText("Opciones");
        btnAdminOpciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdminOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminOpcionesMouseClicked(evt);
            }
        });

        btnAdminDesconectar.setText("Desconectar");
        btnAdminDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDesconectarActionPerformed(evt);
            }
        });
        btnAdminOpciones.add(btnAdminDesconectar);

        btnAdminResContrasena.setText("Restablecer contrasena a un usuario");
        btnAdminOpciones.add(btnAdminResContrasena);

        menuElegirTema.setText("Elegir tema");

        btnElegirTemaSalmon.setText("Salmón");
        menuElegirTema.add(btnElegirTemaSalmon);

        btnElegirTemaAzul.setText("Azul ballena");
        btnElegirTemaAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirTemaAzulActionPerformed(evt);
            }
        });
        menuElegirTema.add(btnElegirTemaAzul);

        btnElegirTemaVerde.setText("Verde médico");
        btnElegirTemaVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirTemaVerdeActionPerformed(evt);
            }
        });
        menuElegirTema.add(btnElegirTemaVerde);

        btnElegirTemaCustom.setText("Personalizar [...]");
        menuElegirTema.add(btnElegirTemaCustom);

        btnAdminOpciones.add(menuElegirTema);

        menuAdmin.add(btnAdminOpciones);

        setJMenuBar(menuAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCitasActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminVerCitas);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnVerCitasActionPerformed

    private void btnDarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarCitaActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminDarCita);
        panelAdmin.repaint();
        panelAdmin.revalidate();

    }//GEN-LAST:event_btnDarCitaActionPerformed

    private void txtAdminVerCitasTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminVerCitasTotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminVerCitasTotalesActionPerformed

    private void btnAdminOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminOpcionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminOpcionesMouseClicked

    private void btnAdminDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDesconectarActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminDesconectarActionPerformed

    private void btnAdminListarAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminListarAnimalesActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminListarAnimales);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminListarAnimalesActionPerformed

    private void btnAdminAnadirVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAnadirVeterinarioActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminAnadirVeterinario);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminAnadirVeterinarioActionPerformed

    private void txtAdminCrearPersonaDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminCrearPersonaDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminCrearPersonaDniActionPerformed

    private void btnAdminListarAniHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminListarAniHistorialActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminHistorialMed);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminListarAniHistorialActionPerformed

    private void btnAdminListarVeterinariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminListarVeterinariosActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminListarVeterinarios);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminListarVeterinariosActionPerformed

    private void btnAdminListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminListarClientesActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminListarClientes);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminListarClientesActionPerformed

    private void txtAdminAnadirAnimalIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminAnadirAnimalIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminAnadirAnimalIdActionPerformed

    private void btnAdminAnadirAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAnadirAnimalActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminAnadirAnimal);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminAnadirAnimalActionPerformed

    private void btnAdminVerCitasModificarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminVerCitasModificarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminVerCitasModificarCitaActionPerformed

    private void txtAdminCrearPersonaDni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminCrearPersonaDni1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminCrearPersonaDni1ActionPerformed

    private void btnAdminAnadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAnadirClienteActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminAnadirCliente);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminAnadirClienteActionPerformed

    private void btnElegirTemaAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirTemaAzulActionPerformed
        r = 155;
        g = 124;
        b = 255;
        Color ballena = new Color(r, g, b);
        panelAdmin.setBackground(ballena);
    }//GEN-LAST:event_btnElegirTemaAzulActionPerformed

    private void btnElegirTemaVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirTemaVerdeActionPerformed
        r = 137;
        g = 255;
        b = 124;
        Color medico = new Color(r, g, b);
        panelAdmin.setBackground(Color.green);
        panelAdmin.repaint();
    }//GEN-LAST:event_btnElegirTemaVerdeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAdminAnimales;
    private javax.swing.JMenuItem btnAdminAnadirAnimal;
    private javax.swing.JMenuItem btnAdminAnadirCliente;
    private javax.swing.JMenuItem btnAdminAnadirVeterinario;
    private javax.swing.JMenu btnAdminCitas;
    private javax.swing.JButton btnAdminDarCitaAceptar;
    private javax.swing.JButton btnAdminDarCitaAceptar1;
    private javax.swing.JButton btnAdminDarCitaAceptar2;
    private javax.swing.JButton btnAdminDarCitaAceptar3;
    private javax.swing.JButton btnAdminDarCitaCancelar;
    private javax.swing.JButton btnAdminDarCitaCancelar1;
    private javax.swing.JButton btnAdminDarCitaCancelar2;
    private javax.swing.JButton btnAdminDarCitaCancelar3;
    private javax.swing.JMenuItem btnAdminDesconectar;
    private javax.swing.JButton btnAdminListarAniBorrar;
    private javax.swing.JButton btnAdminListarAniHistorial;
    private javax.swing.JButton btnAdminListarAniMod;
    private javax.swing.JMenuItem btnAdminListarAnimales;
    private javax.swing.JMenuItem btnAdminListarClientes;
    private javax.swing.JButton btnAdminListarClientesBorrar;
    private javax.swing.JButton btnAdminListarClientesMod;
    private javax.swing.JMenuItem btnAdminListarVeterinarios;
    private javax.swing.JButton btnAdminListarVeterinariosBorrar;
    private javax.swing.JButton btnAdminListarVeterinariosMod;
    private javax.swing.JMenu btnAdminOpciones;
    private javax.swing.JMenuItem btnAdminResContrasena;
    private javax.swing.JMenu btnAdminUsuarios;
    private javax.swing.JButton btnAdminVerAnotacion;
    private javax.swing.JButton btnAdminVerCitasAtenderCita;
    private javax.swing.JButton btnAdminVerCitasCancelarCita;
    private javax.swing.JButton btnAdminVerCitasModificarCita;
    private javax.swing.JMenuItem btnDarCita;
    private javax.swing.JMenuItem btnElegirTemaAzul;
    private javax.swing.JMenuItem btnElegirTemaCustom;
    private javax.swing.JMenuItem btnElegirTemaSalmon;
    private javax.swing.JMenuItem btnElegirTemaVerde;
    private javax.swing.JMenuItem btnVerCitas;
    private com.toedter.calendar.JDateChooser calendarAdminAnadirAnimalNacimiento;
    private javax.swing.JComboBox<String> comboAdminAnadirPersonaEspe;
    private javax.swing.JComboBox<String> comboAdminDarCitaAsunto;
    private javax.swing.ButtonGroup groupBtnAdminAnadirUsuario;
    private javax.swing.ButtonGroup groupBtnAdminDarCita;
    private com.toedter.calendar.JDateChooser jCalendarAdminDarCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel labelCitasTotales;
    private javax.swing.JList<String> listAdminHorasDisponibles;
    private javax.swing.JMenuBar menuAdmin;
    private javax.swing.JMenu menuElegirTema;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JPanel panelAdminAnadirAnimal;
    private javax.swing.JPanel panelAdminAnadirCliente;
    private javax.swing.JPanel panelAdminAnadirVeterinario;
    private javax.swing.JPanel panelAdminDarCita;
    private javax.swing.JPanel panelAdminHistorialMed;
    private javax.swing.JPanel panelAdminInicio;
    private javax.swing.JPanel panelAdminListarAnimales;
    private javax.swing.JPanel panelAdminListarClientes;
    private javax.swing.JPanel panelAdminListarVeterinarios;
    private javax.swing.JPanel panelAdminVerCitas;
    private javax.swing.JRadioButton radioAdminAnadirUsuPriviNo;
    private javax.swing.JRadioButton radioAdminAnadirUsuPriviNo1;
    private javax.swing.JRadioButton radioAdminAnadirUsuPriviSi;
    private javax.swing.JRadioButton radioAdminAnadirUsuPriviSi1;
    private javax.swing.JScrollPane scrollAdminHistorialMed;
    private javax.swing.JScrollPane scrollAdminHorasDisponibles;
    private javax.swing.JScrollPane scrollAdminListarAnimales;
    private javax.swing.JScrollPane scrollAdminListarClientes;
    private javax.swing.JScrollPane scrollAdminListarClientes1;
    private javax.swing.JScrollPane scrollAdminVerCitas;
    private javax.swing.JSpinner spinnerAdminAnadirAnimalPeso;
    private javax.swing.JTable tablaAdminHistorialMed;
    private javax.swing.JTable tableAdminListarAnimales;
    private javax.swing.JTable tableAdminListarClientes;
    private javax.swing.JTable tableAdminListarVeterinarios;
    private javax.swing.JTable tableAdminVerCitas;
    private javax.swing.JTextField txtAdminAnadirAnimalEspecie;
    private javax.swing.JTextField txtAdminAnadirAnimalEspecie1;
    private javax.swing.JTextField txtAdminAnadirAnimalId;
    private javax.swing.JTextField txtAdminAnadirAnimalNombre;
    private javax.swing.JTextField txtAdminAnadirAnimalRaza;
    private javax.swing.JTextField txtAdminAnadirPersonaDire;
    private javax.swing.JTextField txtAdminAnadirPersonaDire1;
    private javax.swing.JTextField txtAdminAnadirPersonaEmail;
    private javax.swing.JTextField txtAdminAnadirPersonaEmail1;
    private javax.swing.JTextField txtAdminAnadirPersonaNombre;
    private javax.swing.JTextField txtAdminAnadirPersonaNombre1;
    private javax.swing.JTextField txtAdminAnadirPersonaTlf;
    private javax.swing.JTextField txtAdminAnadirPersonaTlf1;
    private javax.swing.JTextField txtAdminCrearPersonaDni;
    private javax.swing.JTextField txtAdminCrearPersonaDni1;
    private javax.swing.JTextField txtAdminDarCitaAnimal;
    private javax.swing.JTextField txtAdminDarCitaVet;
    private javax.swing.JTextField txtAdminVerCitasTotales;
    // End of variables declaration//GEN-END:variables
}
