/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import java.awt.Color;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Box;

/**
 *
 * @author Ghoul
 */
public class PanelAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form PanelVeterinario
     */
    int r = 0;
    int g = 0;
    int b = 0;

    public PanelAdministrador() {
        initComponents();

        DateFormat variableFecha = DateFormat.getDateInstance();
        Calendar cal = Calendar.getInstance();
        Date today = cal.getTime();
        cal.add(Calendar.YEAR, 1);
        Date nextYear = cal.getTime();
        jCalendarAdminDarCita.setMaxSelectableDate(nextYear);

        panelAdminVerCitas.setVisible(false);

        menuAdmin.add(Box.createHorizontalGlue());
        menuAdmin.add(btnAdminOpciones);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBtnAdminAñadirUsuario = new javax.swing.ButtonGroup();
        groupBtnAdminDarCita = new javax.swing.ButtonGroup();
        panelAdmin = new javax.swing.JPanel();
        panelAdminInicio = new javax.swing.JPanel();
        panelAdminDarCita = new javax.swing.JPanel();
        scrollAdminHorasDisponibles = new javax.swing.JScrollPane();
        listAdminHorasDisponibles = new javax.swing.JList<String>();
        txtAdminDarCitaAnimal = new javax.swing.JTextField();
        comboAdminDarCitaAsunto = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAdminDarCitaAceptar = new javax.swing.JButton();
        btnAdminDarCitaCancelar = new javax.swing.JButton();
        jCalendarAdminDarCita = new com.toedter.calendar.JDateChooser();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        comoBoxVet = new javax.swing.JComboBox();
        panelAdminVerCitas = new javax.swing.JPanel();
        btnAdminVerCitasCancelarCita = new javax.swing.JButton();
        labelCitasTotales = new javax.swing.JLabel();
        txtAdminVerCitasTotales = new javax.swing.JTextField();
        btnAdminVerCitasModificarCita = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdminVerCitasAtenderCita = new javax.swing.JButton();
        scrollAdminVerCitas = new javax.swing.JScrollPane();
        tableAdminVerCitas = new javax.swing.JTable();
        panelAdminListarAnimales = new javax.swing.JPanel();
        btnAdminListarAniHistorial = new javax.swing.JButton();
        btnAdminListarAniMod = new javax.swing.JButton();
        btnAdminListarAniBorrar = new javax.swing.JButton();
        scrollAdminListarAnimales = new javax.swing.JScrollPane();
        tableAdminListarAnimales = new javax.swing.JTable();
        panelAdminHistorialMed = new javax.swing.JPanel();
        scrollAdminHistorialMed = new javax.swing.JScrollPane();
        tablaAdminHistorialMed = new javax.swing.JTable();
        btnAdminVerAnotacion = new javax.swing.JButton();
        panelAdminAñadirVeterinario = new javax.swing.JPanel();
        txtAdminAñadirVetDni = new javax.swing.JTextField();
        txtAdminAñadirVetNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        radioAdminAñadirVetPriviSi = new javax.swing.JRadioButton();
        radioAdminAñadirVetPriviNo = new javax.swing.JRadioButton();
        btnAdminAñadirVetAceptar = new javax.swing.JButton();
        btnAdminAñadirVetCancelar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtAdminAñadirVetDire = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtAdminAñadirVetTlf = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txtAdminAñadirVetEmail = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        comboAdminAñadirVetEspe = new javax.swing.JComboBox<String>();
        jSeparator9 = new javax.swing.JSeparator();
        passAdminAñadirVet = new javax.swing.JPasswordField();
        panelAdminListarClientes = new javax.swing.JPanel();
        btnAdminListarClientesMod = new javax.swing.JButton();
        btnAdminListarClientesBorrar = new javax.swing.JButton();
        scrollAdminListarClientes = new javax.swing.JScrollPane();
        tableAdminListarClientes = new javax.swing.JTable();
        panelAdminListarVeterinarios = new javax.swing.JPanel();
        btnAdminListarVeterinariosMod = new javax.swing.JButton();
        btnAdminListarVeterinariosBorrar = new javax.swing.JButton();
        scrollAdminListarClientes1 = new javax.swing.JScrollPane();
        tableAdminListarVeterinarios = new javax.swing.JTable();
        panelAdminAñadirAnimal = new javax.swing.JPanel();
        txtAdminAñadirAnimalId = new javax.swing.JTextField();
        txtAdminAñadirAnimalNombre = new javax.swing.JTextField();
        btnAdminDarCitaAceptar2 = new javax.swing.JButton();
        btnAdminDarCitaCancelar2 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        txtAdminAñadirAnimalRaza = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        txtAdminAñadirAnimalEspecie = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        spinnerAdminAñadirAnimalPeso = new javax.swing.JSpinner();
        calendarAdminAñadirAnimalNacimiento = new com.toedter.calendar.JDateChooser();
        txtAdminAñadirAnimalEspecie1 = new javax.swing.JTextField();
        panelAdminAñadirCliente = new javax.swing.JPanel();
        txtAdminAñadirClienteDni = new javax.swing.JTextField();
        txtAdminAñadirClienteNombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        radioAdminAñadirClientePriviSi = new javax.swing.JRadioButton();
        radioAdminAñadirClientePriviNo = new javax.swing.JRadioButton();
        btnAdminAñadirUsuarioAceptar = new javax.swing.JButton();
        btnAdminAñadirUsuarioCancelar = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        txtAdminAñadirClienteDire = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        txtAdminAñadirClienteTlf = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        txtAdminAñadirClienteEmail = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        passAdminAñadirCliente = new javax.swing.JPasswordField();
        menuAdmin = new javax.swing.JMenuBar();
        btnAdminCitas = new javax.swing.JMenu();
        btnDarCita = new javax.swing.JMenuItem();
        btnVerCitas = new javax.swing.JMenuItem();
        btnAdminAnimales = new javax.swing.JMenu();
        btnAdminAnadirAnimal = new javax.swing.JMenuItem();
        btnAdminListarAnimales = new javax.swing.JMenuItem();
        btnAdminUsuarios = new javax.swing.JMenu();
        btnAdminAnadirCliente = new javax.swing.JMenuItem();
        btnAdminAnadirVeterinario = new javax.swing.JMenuItem();
        btnAdminListarClientes = new javax.swing.JMenuItem();
        btnAdminListarVeterinarios = new javax.swing.JMenuItem();
        btnAdminOpciones = new javax.swing.JMenu();
        btnAdminDesconectar = new javax.swing.JMenuItem();
        btnAdminResContraseña = new javax.swing.JMenuItem();
        menuElegirTema = new javax.swing.JMenu();
        btnElegirTemaSalmon = new javax.swing.JMenuItem();
        btnElegirTemaAzul = new javax.swing.JMenuItem();
        btnElegirTemaVerde = new javax.swing.JMenuItem();
        btnElegirTemaCustom = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAdmin.setBackground(new java.awt.Color(255, 204, 204));
        panelAdmin.setLayout(new java.awt.CardLayout());

        panelAdminInicio.setBackground(panelAdmin.getBackground());

        javax.swing.GroupLayout panelAdminInicioLayout = new javax.swing.GroupLayout(panelAdminInicio);
        panelAdminInicio.setLayout(panelAdminInicioLayout);
        panelAdminInicioLayout.setHorizontalGroup(
            panelAdminInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelAdminInicioLayout.setVerticalGroup(
            panelAdminInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelAdmin.add(panelAdminInicio, "card4");

        panelAdminDarCita.setBackground(panelAdmin.getBackground());

        scrollAdminHorasDisponibles.setViewportView(listAdminHorasDisponibles);

        txtAdminDarCitaAnimal.setBackground(panelAdmin.getBackground());
        txtAdminDarCitaAnimal.setText("Animal");
        txtAdminDarCitaAnimal.setBorder(null);

        jLabel4.setText("Asunto");

        jLabel5.setText("Día");

        jLabel7.setText("Horas disponibles");

        btnAdminDarCitaAceptar.setText("Aceptar");

        btnAdminDarCitaCancelar.setText("Cancelar");

        jCalendarAdminDarCita.setBackground(panelAdminInicio.getBackground());

        jLabel2.setText("Veterinario");

        javax.swing.GroupLayout panelAdminDarCitaLayout = new javax.swing.GroupLayout(panelAdminDarCita);
        panelAdminDarCita.setLayout(panelAdminDarCitaLayout);
        panelAdminDarCitaLayout.setHorizontalGroup(
            panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAdminDarCitaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                            .addComponent(btnAdminDarCitaAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)
                            .addComponent(btnAdminDarCitaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(comboAdminDarCitaAsunto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(4, 4, 4)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAdminDarCitaLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comoBoxVet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAdminDarCitaLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(27, 27, 27)
                            .addComponent(jCalendarAdminDarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(scrollAdminHorasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminDarCitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(238, 238, 238))
        );
        panelAdminDarCitaLayout.setVerticalGroup(
            panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollAdminHorasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAdminDarCitaLayout.createSequentialGroup()
                        .addComponent(txtAdminDarCitaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboAdminDarCitaAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(69, 69, 69)
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalendarAdminDarCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(56, 56, 56)
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comoBoxVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAdminDarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdminDarCitaCancelar)
                            .addComponent(btnAdminDarCitaAceptar))))
                .addGap(18, 18, 18))
        );

        panelAdmin.add(panelAdminDarCita, "card5");

        panelAdminVerCitas.setBackground(panelAdmin.getBackground());

        btnAdminVerCitasCancelarCita.setText("Cancelar cita seleccionada");

        labelCitasTotales.setText("Citas totales");

        txtAdminVerCitasTotales.setEditable(false);
        txtAdminVerCitasTotales.setBackground(panelAdmin.getBackground());
        txtAdminVerCitasTotales.setBorder(null);
        txtAdminVerCitasTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminVerCitasTotalesActionPerformed(evt);
            }
        });

        btnAdminVerCitasModificarCita.setText("Modificar cita seleccionada");
        btnAdminVerCitasModificarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminVerCitasModificarCitaActionPerformed(evt);
            }
        });

        btnAdminVerCitasAtenderCita.setText("Atender cita seleccionada");

        tableAdminVerCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminVerCitas.setViewportView(tableAdminVerCitas);

        javax.swing.GroupLayout panelAdminVerCitasLayout = new javax.swing.GroupLayout(panelAdminVerCitas);
        panelAdminVerCitas.setLayout(panelAdminVerCitasLayout);
        panelAdminVerCitasLayout.setHorizontalGroup(
            panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                .addGroup(panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                        .addGroup(panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminVerCitasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelCitasTotales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAdminVerCitasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdminVerCitasAtenderCita, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdminVerCitasModificarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdminVerCitasCancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollAdminVerCitas)))
                .addContainerGap())
        );
        panelAdminVerCitasLayout.setVerticalGroup(
            panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollAdminVerCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminVerCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdminVerCitasModificarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdminVerCitasCancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAdminVerCitasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCitasTotales)
                        .addComponent(btnAdminVerCitasAtenderCita, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdminVerCitasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAdmin.add(panelAdminVerCitas, "card4");

        panelAdminListarAnimales.setBackground(panelAdmin.getBackground());

        btnAdminListarAniHistorial.setText("Ver historial médico del animal");
        btnAdminListarAniHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminListarAniHistorialActionPerformed(evt);
            }
        });

        btnAdminListarAniMod.setText("Modificar datos del animal");

        btnAdminListarAniBorrar.setText("Borrar animal seleccionado");

        tableAdminListarAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminListarAnimales.setViewportView(tableAdminListarAnimales);

        javax.swing.GroupLayout panelAdminListarAnimalesLayout = new javax.swing.GroupLayout(panelAdminListarAnimales);
        panelAdminListarAnimales.setLayout(panelAdminListarAnimalesLayout);
        panelAdminListarAnimalesLayout.setHorizontalGroup(
            panelAdminListarAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarAnimalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminListarAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollAdminListarAnimales)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminListarAnimalesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdminListarAniMod, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminListarAniHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminListarAniBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAdminListarAnimalesLayout.setVerticalGroup(
            panelAdminListarAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarAnimalesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scrollAdminListarAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdminListarAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminListarAniMod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminListarAniHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminListarAniBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        panelAdmin.add(panelAdminListarAnimales, "card4");

        panelAdminHistorialMed.setBackground(panelAdmin.getBackground());

        tablaAdminHistorialMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminHistorialMed.setViewportView(tablaAdminHistorialMed);

        btnAdminVerAnotacion.setText("Ver anotación completa");

        javax.swing.GroupLayout panelAdminHistorialMedLayout = new javax.swing.GroupLayout(panelAdminHistorialMed);
        panelAdminHistorialMed.setLayout(panelAdminHistorialMedLayout);
        panelAdminHistorialMedLayout.setHorizontalGroup(
            panelAdminHistorialMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminHistorialMedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminHistorialMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAdminHistorialMedLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdminVerAnotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollAdminHistorialMed, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAdminHistorialMedLayout.setVerticalGroup(
            panelAdminHistorialMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminHistorialMedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollAdminHistorialMed, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnAdminVerAnotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAdmin.add(panelAdminHistorialMed, "card4");

        panelAdminAñadirVeterinario.setBackground(panelAdmin.getBackground());

        txtAdminAñadirVetDni.setEditable(false);
        txtAdminAñadirVetDni.setBackground(panelAdmin.getBackground());
        txtAdminAñadirVetDni.setText("DNI");
        txtAdminAñadirVetDni.setBorder(null);
        txtAdminAñadirVetDni.setDisabledTextColor(panelAdminInicio.getBackground());
        txtAdminAñadirVetDni.setFocusable(false);
        txtAdminAñadirVetDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminAñadirVetDniActionPerformed(evt);
            }
        });

        txtAdminAñadirVetNombre.setBackground(panelAdmin.getBackground());
        txtAdminAñadirVetNombre.setText("Nombre");
        txtAdminAñadirVetNombre.setBorder(null);

        jLabel12.setText("Privilegios de administrador");

        radioAdminAñadirVetPriviSi.setBackground(panelAdmin.getBackground());
        groupBtnAdminAñadirUsuario.add(radioAdminAñadirVetPriviSi);
        radioAdminAñadirVetPriviSi.setText("Sí");

        radioAdminAñadirVetPriviNo.setBackground(panelAdmin.getBackground());
        groupBtnAdminAñadirUsuario.add(radioAdminAñadirVetPriviNo);
        radioAdminAñadirVetPriviNo.setText("No");

        btnAdminAñadirVetAceptar.setText("Aceptar");
        btnAdminAñadirVetAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAñadirVetAceptarActionPerformed(evt);
            }
        });

        btnAdminAñadirVetCancelar.setText("Cancelar");

        txtAdminAñadirVetDire.setBackground(panelAdmin.getBackground());
        txtAdminAñadirVetDire.setText("Dirección");
        txtAdminAñadirVetDire.setBorder(null);
        txtAdminAñadirVetDire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminAñadirVetDireActionPerformed(evt);
            }
        });

        txtAdminAñadirVetTlf.setBackground(panelAdmin.getBackground());
        txtAdminAñadirVetTlf.setText("Teléfono");
        txtAdminAñadirVetTlf.setBorder(null);

        txtAdminAñadirVetEmail.setBackground(panelAdmin.getBackground());
        txtAdminAñadirVetEmail.setText("Email");
        txtAdminAñadirVetEmail.setBorder(null);

        jLabel1.setText("Especialidad");

        comboAdminAñadirVetEspe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        passAdminAñadirVet.setBackground(panelAdmin.getBackground());
        passAdminAñadirVet.setText("Contraseña");
        passAdminAñadirVet.setToolTipText("");
        passAdminAñadirVet.setBorder(null);

        javax.swing.GroupLayout panelAdminAñadirVeterinarioLayout = new javax.swing.GroupLayout(panelAdminAñadirVeterinario);
        panelAdminAñadirVeterinario.setLayout(panelAdminAñadirVeterinarioLayout);
        panelAdminAñadirVeterinarioLayout.setHorizontalGroup(
            panelAdminAñadirVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAñadirVeterinarioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelAdminAñadirVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAdminAñadirVetTlf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAñadirVetEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAdminAñadirVeterinarioLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(37, 37, 37)
                        .addComponent(radioAdminAñadirVetPriviSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioAdminAñadirVetPriviNo))
                    .addGroup(panelAdminAñadirVeterinarioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboAdminAñadirVetEspe, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminAñadirVeterinarioLayout.createSequentialGroup()
                        .addComponent(btnAdminAñadirVetAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdminAñadirVetCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAñadirVetDire, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAñadirVetNombre)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAñadirVetDni)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator9)
                    .addComponent(passAdminAñadirVet, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAdminAñadirVeterinarioLayout.setVerticalGroup(
            panelAdminAñadirVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAñadirVeterinarioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtAdminAñadirVetDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdminAñadirVetNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(txtAdminAñadirVetDire, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdminAñadirVetTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAdminAñadirVetEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(panelAdminAñadirVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboAdminAñadirVetEspe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(passAdminAñadirVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdminAñadirVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(radioAdminAñadirVetPriviSi)
                    .addComponent(radioAdminAñadirVetPriviNo))
                .addGap(18, 18, 18)
                .addGroup(panelAdminAñadirVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminAñadirVetCancelar)
                    .addComponent(btnAdminAñadirVetAceptar))
                .addGap(18, 18, 18))
        );

        panelAdmin.add(panelAdminAñadirVeterinario, "card5");

        panelAdminListarClientes.setBackground(panelAdmin.getBackground());

        btnAdminListarClientesMod.setText("Modificar datos del cliente");

        btnAdminListarClientesBorrar.setText("Borrar cliente seleccionado");

        tableAdminListarClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminListarClientes.setViewportView(tableAdminListarClientes);

        javax.swing.GroupLayout panelAdminListarClientesLayout = new javax.swing.GroupLayout(panelAdminListarClientes);
        panelAdminListarClientes.setLayout(panelAdminListarClientesLayout);
        panelAdminListarClientesLayout.setHorizontalGroup(
            panelAdminListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollAdminListarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminListarClientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdminListarClientesMod, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminListarClientesBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAdminListarClientesLayout.setVerticalGroup(
            panelAdminListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarClientesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scrollAdminListarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdminListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminListarClientesMod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminListarClientesBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        panelAdmin.add(panelAdminListarClientes, "card4");

        panelAdminListarVeterinarios.setBackground(panelAdmin.getBackground());

        btnAdminListarVeterinariosMod.setText("Modificar datos del veterinario");

        btnAdminListarVeterinariosBorrar.setText("Borrar veterinario seleccionado");

        tableAdminListarVeterinarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAdminListarClientes1.setViewportView(tableAdminListarVeterinarios);

        javax.swing.GroupLayout panelAdminListarVeterinariosLayout = new javax.swing.GroupLayout(panelAdminListarVeterinarios);
        panelAdminListarVeterinarios.setLayout(panelAdminListarVeterinariosLayout);
        panelAdminListarVeterinariosLayout.setHorizontalGroup(
            panelAdminListarVeterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarVeterinariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminListarVeterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollAdminListarClientes1)
                    .addGroup(panelAdminListarVeterinariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdminListarVeterinariosMod, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnAdminListarVeterinariosBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAdminListarVeterinariosLayout.setVerticalGroup(
            panelAdminListarVeterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminListarVeterinariosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scrollAdminListarClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdminListarVeterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminListarVeterinariosMod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminListarVeterinariosBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        panelAdmin.add(panelAdminListarVeterinarios, "card4");

        panelAdminAñadirAnimal.setBackground(panelAdmin.getBackground());

        txtAdminAñadirAnimalId.setEditable(false);
        txtAdminAñadirAnimalId.setBackground(panelAdminInicio.getBackground());
        txtAdminAñadirAnimalId.setText("ID");
        txtAdminAñadirAnimalId.setBorder(null);
        txtAdminAñadirAnimalId.setDisabledTextColor(panelAdminInicio.getBackground());
        txtAdminAñadirAnimalId.setFocusable(false);

        txtAdminAñadirAnimalNombre.setBackground(panelAdminInicio.getBackground());
        txtAdminAñadirAnimalNombre.setText("Nombre");
        txtAdminAñadirAnimalNombre.setBorder(null);

        btnAdminDarCitaAceptar2.setText("Aceptar");

        btnAdminDarCitaCancelar2.setText("Cancelar");

        txtAdminAñadirAnimalRaza.setBackground(panelAdminInicio.getBackground());
        txtAdminAñadirAnimalRaza.setText("Raza");
        txtAdminAñadirAnimalRaza.setBorder(null);

        txtAdminAñadirAnimalEspecie.setBackground(panelAdminInicio.getBackground());
        txtAdminAñadirAnimalEspecie.setText("Especie");
        txtAdminAñadirAnimalEspecie.setBorder(null);

        jLabel20.setText("Peso");

        jLabel21.setText("Fecha de nacimiento");

        spinnerAdminAñadirAnimalPeso.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(1.0f), null, Float.valueOf(1.0f)));

        calendarAdminAñadirAnimalNacimiento.setBackground(panelAdminInicio.getBackground());

        txtAdminAñadirAnimalEspecie1.setBackground(panelAdminInicio.getBackground());
        txtAdminAñadirAnimalEspecie1.setText("Dueño");
        txtAdminAñadirAnimalEspecie1.setBorder(null);

        javax.swing.GroupLayout panelAdminAñadirAnimalLayout = new javax.swing.GroupLayout(panelAdminAñadirAnimal);
        panelAdminAñadirAnimal.setLayout(panelAdminAñadirAnimalLayout);
        panelAdminAñadirAnimalLayout.setHorizontalGroup(
            panelAdminAñadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAñadirAnimalLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelAdminAñadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminAñadirAnimalLayout.createSequentialGroup()
                        .addComponent(btnAdminDarCitaAceptar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(btnAdminDarCitaCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator10)
                    .addComponent(txtAdminAñadirAnimalId)
                    .addComponent(jSeparator11)
                    .addComponent(txtAdminAñadirAnimalNombre)
                    .addComponent(txtAdminAñadirAnimalRaza)
                    .addComponent(txtAdminAñadirAnimalEspecie)
                    .addComponent(jSeparator15)
                    .addComponent(txtAdminAñadirAnimalEspecie1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAdminAñadirAnimalLayout.createSequentialGroup()
                        .addGroup(panelAdminAñadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAdminAñadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerAdminAñadirAnimalPeso)
                            .addComponent(calendarAdminAñadirAnimalNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAdminAñadirAnimalLayout.setVerticalGroup(
            panelAdminAñadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAñadirAnimalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtAdminAñadirAnimalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdminAñadirAnimalNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(txtAdminAñadirAnimalRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdminAñadirAnimalEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAdminAñadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(spinnerAdminAñadirAnimalPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelAdminAñadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(calendarAdminAñadirAnimalNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(txtAdminAñadirAnimalEspecie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(panelAdminAñadirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminDarCitaAceptar2)
                    .addComponent(btnAdminDarCitaCancelar2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAdmin.add(panelAdminAñadirAnimal, "card5");

        panelAdminAñadirCliente.setBackground(panelAdmin.getBackground());

        txtAdminAñadirClienteDni.setEditable(false);
        txtAdminAñadirClienteDni.setBackground(panelAdmin.getBackground());
        txtAdminAñadirClienteDni.setText("DNI");
        txtAdminAñadirClienteDni.setBorder(null);
        txtAdminAñadirClienteDni.setDisabledTextColor(panelAdminInicio.getBackground());
        txtAdminAñadirClienteDni.setFocusable(false);
        txtAdminAñadirClienteDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminAñadirClienteDniActionPerformed(evt);
            }
        });

        txtAdminAñadirClienteNombre.setBackground(panelAdmin.getBackground());
        txtAdminAñadirClienteNombre.setText("Nombre");
        txtAdminAñadirClienteNombre.setBorder(null);

        jLabel13.setText("Privilegios de administrador");

        radioAdminAñadirClientePriviSi.setBackground(panelAdmin.getBackground());
        groupBtnAdminAñadirUsuario.add(radioAdminAñadirClientePriviSi);
        radioAdminAñadirClientePriviSi.setText("Sí");

        radioAdminAñadirClientePriviNo.setBackground(panelAdmin.getBackground());
        groupBtnAdminAñadirUsuario.add(radioAdminAñadirClientePriviNo);
        radioAdminAñadirClientePriviNo.setText("No");

        btnAdminAñadirUsuarioAceptar.setText("Aceptar");

        btnAdminAñadirUsuarioCancelar.setText("Cancelar");

        txtAdminAñadirClienteDire.setBackground(panelAdmin.getBackground());
        txtAdminAñadirClienteDire.setText("Dirección");
        txtAdminAñadirClienteDire.setBorder(null);

        txtAdminAñadirClienteTlf.setBackground(panelAdmin.getBackground());
        txtAdminAñadirClienteTlf.setText("Teléfono");
        txtAdminAñadirClienteTlf.setBorder(null);

        txtAdminAñadirClienteEmail.setBackground(panelAdmin.getBackground());
        txtAdminAñadirClienteEmail.setText("Email");
        txtAdminAñadirClienteEmail.setBorder(null);

        passAdminAñadirCliente.setBackground(panelAdmin.getBackground());
        passAdminAñadirCliente.setText("Contraseña");
        passAdminAñadirCliente.setToolTipText("");
        passAdminAñadirCliente.setBorder(null);

        javax.swing.GroupLayout panelAdminAñadirClienteLayout = new javax.swing.GroupLayout(panelAdminAñadirCliente);
        panelAdminAñadirCliente.setLayout(panelAdminAñadirClienteLayout);
        panelAdminAñadirClienteLayout.setHorizontalGroup(
            panelAdminAñadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAñadirClienteLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelAdminAñadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAdminAñadirClienteTlf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAñadirClienteEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminAñadirClienteLayout.createSequentialGroup()
                        .addComponent(btnAdminAñadirUsuarioAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(btnAdminAñadirUsuarioCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAñadirClienteDire, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAñadirClienteNombre)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminAñadirClienteDni)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator20)
                    .addComponent(passAdminAñadirCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAdminAñadirClienteLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(37, 37, 37)
                        .addComponent(radioAdminAñadirClientePriviSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioAdminAñadirClientePriviNo)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAdminAñadirClienteLayout.setVerticalGroup(
            panelAdminAñadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminAñadirClienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtAdminAñadirClienteDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdminAñadirClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(txtAdminAñadirClienteDire, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdminAñadirClienteTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAdminAñadirClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(passAdminAñadirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdminAñadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(radioAdminAñadirClientePriviSi)
                    .addComponent(radioAdminAñadirClientePriviNo))
                .addGap(59, 59, 59)
                .addGroup(panelAdminAñadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminAñadirUsuarioCancelar)
                    .addComponent(btnAdminAñadirUsuarioAceptar))
                .addGap(18, 18, 18))
        );

        panelAdmin.add(panelAdminAñadirCliente, "card5");

        menuAdmin.setBackground(new java.awt.Color(250, 250, 250));
        menuAdmin.setToolTipText("");
        menuAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAdminCitas.setText("Citas");
        btnAdminCitas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnDarCita.setText("Dar cita");
        btnDarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarCitaActionPerformed(evt);
            }
        });
        btnAdminCitas.add(btnDarCita);

        btnVerCitas.setText("Ver citas");
        btnVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCitasActionPerformed(evt);
            }
        });
        btnAdminCitas.add(btnVerCitas);

        menuAdmin.add(btnAdminCitas);

        btnAdminAnimales.setText("Animales");
        btnAdminAnimales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAdminAnadirAnimal.setText("Añadir animal");
        btnAdminAnadirAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAnadirAnimalActionPerformed(evt);
            }
        });
        btnAdminAnimales.add(btnAdminAnadirAnimal);

        btnAdminListarAnimales.setText("Listar animales");
        btnAdminListarAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminListarAnimalesActionPerformed(evt);
            }
        });
        btnAdminAnimales.add(btnAdminListarAnimales);

        menuAdmin.add(btnAdminAnimales);

        btnAdminUsuarios.setText("Usuarios");
        btnAdminUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAdminAnadirCliente.setText("Añadir cliente");
        btnAdminAnadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAnadirClienteActionPerformed(evt);
            }
        });
        btnAdminUsuarios.add(btnAdminAnadirCliente);

        btnAdminAnadirVeterinario.setText("Añadir veterinario");
        btnAdminAnadirVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAnadirVeterinarioActionPerformed(evt);
            }
        });
        btnAdminUsuarios.add(btnAdminAnadirVeterinario);

        btnAdminListarClientes.setText("Listar clientes");
        btnAdminListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminListarClientesActionPerformed(evt);
            }
        });
        btnAdminUsuarios.add(btnAdminListarClientes);

        btnAdminListarVeterinarios.setText("Listar veterinarios");
        btnAdminListarVeterinarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminListarVeterinariosActionPerformed(evt);
            }
        });
        btnAdminUsuarios.add(btnAdminListarVeterinarios);

        menuAdmin.add(btnAdminUsuarios);

        btnAdminOpciones.setText("Opciones");
        btnAdminOpciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdminOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminOpcionesMouseClicked(evt);
            }
        });

        btnAdminDesconectar.setText("Desconectar");
        btnAdminDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDesconectarActionPerformed(evt);
            }
        });
        btnAdminOpciones.add(btnAdminDesconectar);

        btnAdminResContraseña.setText("Restablecer contraseña a un usuario");
        btnAdminOpciones.add(btnAdminResContraseña);

        menuElegirTema.setText("Elegir tema");

        btnElegirTemaSalmon.setText("Salmón");
        menuElegirTema.add(btnElegirTemaSalmon);

        btnElegirTemaAzul.setText("Azul ballena");
        btnElegirTemaAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirTemaAzulActionPerformed(evt);
            }
        });
        menuElegirTema.add(btnElegirTemaAzul);

        btnElegirTemaVerde.setText("Verde médico");
        btnElegirTemaVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirTemaVerdeActionPerformed(evt);
            }
        });
        menuElegirTema.add(btnElegirTemaVerde);

        btnElegirTemaCustom.setText("Personalizar [...]");
        menuElegirTema.add(btnElegirTemaCustom);

        btnAdminOpciones.add(menuElegirTema);

        menuAdmin.add(btnAdminOpciones);

        setJMenuBar(menuAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCitasActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminVerCitas);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnVerCitasActionPerformed

    private void btnDarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarCitaActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminDarCita);
        panelAdmin.repaint();
        panelAdmin.revalidate();

    }//GEN-LAST:event_btnDarCitaActionPerformed

    private void txtAdminVerCitasTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminVerCitasTotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminVerCitasTotalesActionPerformed

    private void btnAdminOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminOpcionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminOpcionesMouseClicked

    private void btnAdminDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDesconectarActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminDesconectarActionPerformed

    private void btnAdminListarAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminListarAnimalesActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminListarAnimales);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminListarAnimalesActionPerformed

    private void btnAdminAnadirVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAnadirVeterinarioActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminAñadirVeterinario);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminAnadirVeterinarioActionPerformed

    private void txtAdminAñadirVetDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminAñadirVetDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminAñadirVetDniActionPerformed

    private void btnAdminListarAniHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminListarAniHistorialActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminHistorialMed);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminListarAniHistorialActionPerformed

    private void btnAdminListarVeterinariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminListarVeterinariosActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminListarVeterinarios);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminListarVeterinariosActionPerformed

    private void btnAdminListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminListarClientesActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminListarClientes);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminListarClientesActionPerformed

    private void txtAdminAnadirAnimalIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminAnadirAnimalIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminAnadirAnimalIdActionPerformed

    private void btnAdminAnadirAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAnadirAnimalActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminAñadirAnimal);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminAnadirAnimalActionPerformed

    private void btnAdminVerCitasModificarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminVerCitasModificarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminVerCitasModificarCitaActionPerformed

    private void txtAdminAñadirClienteDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminAñadirClienteDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminAñadirClienteDniActionPerformed

    private void btnAdminAnadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAnadirClienteActionPerformed
        panelAdmin.removeAll();
        panelAdmin.add(panelAdminAñadirCliente);
        panelAdmin.repaint();
        panelAdmin.revalidate();
    }//GEN-LAST:event_btnAdminAnadirClienteActionPerformed

    private void btnElegirTemaAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirTemaAzulActionPerformed
        r = 155;
        g = 124;
        b = 255;
        Color ballena = new Color(r, g, b);
        panelAdmin.setBackground(ballena);
    }//GEN-LAST:event_btnElegirTemaAzulActionPerformed

    private void btnElegirTemaVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirTemaVerdeActionPerformed
        r = 137;
        g = 255;
        b = 124;
        Color medico = new Color(r, g, b);
        panelAdmin.setBackground(Color.green);
        panelAdmin.repaint();
    }//GEN-LAST:event_btnElegirTemaVerdeActionPerformed

    private void btnAdminAñadirVetAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAñadirVetAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminAñadirVetAceptarActionPerformed

    private void txtAdminAñadirVetDireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminAñadirVetDireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminAñadirVetDireActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAdminAnadirAnimal;
    private javax.swing.JMenuItem btnAdminAnadirCliente;
    private javax.swing.JMenuItem btnAdminAnadirVeterinario;
    private javax.swing.JMenu btnAdminAnimales;
    public javax.swing.JButton btnAdminAñadirUsuarioAceptar;
    public javax.swing.JButton btnAdminAñadirUsuarioCancelar;
    public javax.swing.JButton btnAdminAñadirVetAceptar;
    public javax.swing.JButton btnAdminAñadirVetCancelar;
    private javax.swing.JMenu btnAdminCitas;
    public javax.swing.JButton btnAdminDarCitaAceptar;
    public javax.swing.JButton btnAdminDarCitaAceptar2;
    public javax.swing.JButton btnAdminDarCitaCancelar;
    public javax.swing.JButton btnAdminDarCitaCancelar2;
    private javax.swing.JMenuItem btnAdminDesconectar;
    public javax.swing.JButton btnAdminListarAniBorrar;
    public javax.swing.JButton btnAdminListarAniHistorial;
    public javax.swing.JButton btnAdminListarAniMod;
    private javax.swing.JMenuItem btnAdminListarAnimales;
    private javax.swing.JMenuItem btnAdminListarClientes;
    public javax.swing.JButton btnAdminListarClientesBorrar;
    public javax.swing.JButton btnAdminListarClientesMod;
    private javax.swing.JMenuItem btnAdminListarVeterinarios;
    public javax.swing.JButton btnAdminListarVeterinariosBorrar;
    public javax.swing.JButton btnAdminListarVeterinariosMod;
    private javax.swing.JMenu btnAdminOpciones;
    private javax.swing.JMenuItem btnAdminResContraseña;
    private javax.swing.JMenu btnAdminUsuarios;
    public javax.swing.JButton btnAdminVerAnotacion;
    public javax.swing.JButton btnAdminVerCitasAtenderCita;
    public javax.swing.JButton btnAdminVerCitasCancelarCita;
    public javax.swing.JButton btnAdminVerCitasModificarCita;
    private javax.swing.JMenuItem btnDarCita;
    private javax.swing.JMenuItem btnElegirTemaAzul;
    private javax.swing.JMenuItem btnElegirTemaCustom;
    private javax.swing.JMenuItem btnElegirTemaSalmon;
    private javax.swing.JMenuItem btnElegirTemaVerde;
    private javax.swing.JMenuItem btnVerCitas;
    public com.toedter.calendar.JDateChooser calendarAdminAñadirAnimalNacimiento;
    public javax.swing.JComboBox<String> comboAdminAñadirVetEspe;
    public javax.swing.JComboBox<String> comboAdminDarCitaAsunto;
    public javax.swing.JComboBox comoBoxVet;
    private javax.swing.ButtonGroup groupBtnAdminAñadirUsuario;
    private javax.swing.ButtonGroup groupBtnAdminDarCita;
    public com.toedter.calendar.JDateChooser jCalendarAdminDarCita;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator10;
    public javax.swing.JSeparator jSeparator11;
    public javax.swing.JSeparator jSeparator12;
    public javax.swing.JSeparator jSeparator13;
    public javax.swing.JSeparator jSeparator14;
    public javax.swing.JSeparator jSeparator15;
    public javax.swing.JSeparator jSeparator16;
    public javax.swing.JSeparator jSeparator17;
    public javax.swing.JSeparator jSeparator18;
    public javax.swing.JSeparator jSeparator19;
    public javax.swing.JSeparator jSeparator20;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JSeparator jSeparator5;
    public javax.swing.JSeparator jSeparator6;
    public javax.swing.JSeparator jSeparator7;
    public javax.swing.JSeparator jSeparator8;
    public javax.swing.JSeparator jSeparator9;
    public javax.swing.JLabel labelCitasTotales;
    public javax.swing.JList<String> listAdminHorasDisponibles;
    private javax.swing.JMenuBar menuAdmin;
    private javax.swing.JMenu menuElegirTema;
    private javax.swing.JPanel panelAdmin;
    public javax.swing.JPanel panelAdminAñadirAnimal;
    public javax.swing.JPanel panelAdminAñadirCliente;
    public javax.swing.JPanel panelAdminAñadirVeterinario;
    public javax.swing.JPanel panelAdminDarCita;
    public javax.swing.JPanel panelAdminHistorialMed;
    public javax.swing.JPanel panelAdminInicio;
    public javax.swing.JPanel panelAdminListarAnimales;
    public javax.swing.JPanel panelAdminListarClientes;
    public javax.swing.JPanel panelAdminListarVeterinarios;
    public javax.swing.JPanel panelAdminVerCitas;
    public javax.swing.JPasswordField passAdminAñadirCliente;
    public javax.swing.JPasswordField passAdminAñadirVet;
    public javax.swing.JRadioButton radioAdminAñadirClientePriviNo;
    public javax.swing.JRadioButton radioAdminAñadirClientePriviSi;
    public javax.swing.JRadioButton radioAdminAñadirVetPriviNo;
    public javax.swing.JRadioButton radioAdminAñadirVetPriviSi;
    public javax.swing.JScrollPane scrollAdminHistorialMed;
    public javax.swing.JScrollPane scrollAdminHorasDisponibles;
    public javax.swing.JScrollPane scrollAdminListarAnimales;
    public javax.swing.JScrollPane scrollAdminListarClientes;
    public javax.swing.JScrollPane scrollAdminListarClientes1;
    public javax.swing.JScrollPane scrollAdminVerCitas;
    public javax.swing.JSpinner spinnerAdminAñadirAnimalPeso;
    public javax.swing.JTable tablaAdminHistorialMed;
    public javax.swing.JTable tableAdminListarAnimales;
    public javax.swing.JTable tableAdminListarClientes;
    public javax.swing.JTable tableAdminListarVeterinarios;
    public javax.swing.JTable tableAdminVerCitas;
    public javax.swing.JTextField txtAdminAñadirAnimalEspecie;
    public javax.swing.JTextField txtAdminAñadirAnimalEspecie1;
    public javax.swing.JTextField txtAdminAñadirAnimalId;
    public javax.swing.JTextField txtAdminAñadirAnimalNombre;
    public javax.swing.JTextField txtAdminAñadirAnimalRaza;
    public javax.swing.JTextField txtAdminAñadirClienteDire;
    public javax.swing.JTextField txtAdminAñadirClienteDni;
    public javax.swing.JTextField txtAdminAñadirClienteEmail;
    public javax.swing.JTextField txtAdminAñadirClienteNombre;
    public javax.swing.JTextField txtAdminAñadirClienteTlf;
    public javax.swing.JTextField txtAdminAñadirVetDire;
    public javax.swing.JTextField txtAdminAñadirVetDni;
    public javax.swing.JTextField txtAdminAñadirVetEmail;
    public javax.swing.JTextField txtAdminAñadirVetNombre;
    public javax.swing.JTextField txtAdminAñadirVetTlf;
    public javax.swing.JTextField txtAdminDarCitaAnimal;
    public javax.swing.JTextField txtAdminVerCitasTotales;
    // End of variables declaration//GEN-END:variables
}
